#source: http://powershell.com/cs/media/p/19301.aspx (dead link :-()
#modified to use a custom object to avoid creating thousands of public variables

$VIS=[Ordered]@{
#Public Enum VisArcSweepFlags 
ArcSweepFlagConcave = 0 
ArcSweepFlagConvex = 1 
#End Enum 
 
#Public Enum VisAutoConnectDir 
AutoConnectDirDown = 2 
AutoConnectDirLeft = 3 
AutoConnectDirNone = 0 
AutoConnectDirRight = 4 
AutoConnectDirUp = 1 
#End Enum 
 
#Public Enum VisAutoLinkBehaviors 
AutoLinkDontReplaceExistingLinks = 16 
AutoLinkGenericProgressBar = 2 
AutoLinkIncludeHiddenProps = 64 
AutoLinkNoApplyDataGraphic = 4 
AutolinkNullMatchesNoFormula = 32 
AutoLinkReplaceExistingLinks = 8 
AutoLinkSelectedShapesOnly = 1 
#End Enum 
 
#Public Enum VisAutoLinkFieldTypes 
AutoLinkCustPropsLabel = 2 
AutoLinkGeometryAngle = 4 
AutoLinkGeometryHeight = 6 
AutoLinkGeometryWidth = 5 
AutoLinkMasterName = 8 
AutoLinkMasterNameU = 16 
AutoLinkObjectData1 = 11 
AutoLinkObjectData2 = 12 
AutoLinkObjectData3 = 13 
AutoLinkObjectID = 7 
AutoLinkObjectName = 9 
AutoLinkObjectNameU = 17 
AutoLinkObjectType = 10 
AutoLinkPropRowNameU = 14 
AutoLinkShapeText = 1 
AutoLinkUserRowName = 3 
AutoLinkUserRowNameU = 15 
#End Enum 
 
#Public Enum VisBoundingBoxArgs 
BBoxDrawingCoords = 0x2000 
BBoxExtents = 0x4 
BBoxIgnoreVisible = 0x20 
BBoxIncludeDataGraphics = 0x10000 
BBoxIncludeGuides = 0x1000 
BBoxIncludeHidden = 0x10 
BBoxNoNonPrint = 0x4000 
BBoxUprightText = 0x2 
BBoxUprightWH = 0x1 
#End Enum 
 
#Public Enum VisCellError 
ErrorDivideByZero = 39 
ErrorName = 61 
ErrorNotAvailable = 74 
ErrorNumber = 68 
ErrorReference = 55 
ErrorSuccess = 0 
ErrorValue = 47 
#End Enum 
 
#Public Enum VisCellIndices 
'1DBeginX' = 0 
'1DBeginY' = 1 
'1DEndX' = 2 
'1DEndY' = 3 
ActionAction = 3 
ActionBeginGroup = 8 
ActionButtonFace = 15 
ActionChecked = 4 
ActionDisabled = 5 
ActionInvisible = 7 
ActionMenu = 0 
ActionReadOnly = 6 
ActionSortKey = 16 
ActionTagName = 14 
AlignBottom = 5 
AlignCenter = 1 
AlignLeft = 0 
AlignMiddle = 4 
AlignRight = 2 
AlignTop = 3 
AnnotationComment = 5 
AnnotationDate = 4 
AnnotationLangID = 6 
AnnotationMarkerIndex = 3 
AnnotationReviewerID = 2 
AnnotationX = 0 
AnnotationY = 1 
AspectRatio = 5 
BegTrigger = 11 
Bow = 2 
BulletFontSize = 11 
BulletFont = 9 
BulletIndex = 7 
BulletString = 8 
CellFirst = 0 
CellInval = 255 
CellNone = 255 
CharacterAsianFont = 51 
CharacterCase = 3 
CharacterColorTrans = 17 
CharacterColor = 1 
CharacterComplexScriptFont = 52 
CharacterComplexScriptSize = 54 
CharacterDblUnderline = 8 
CharacterDoubleStrikethrough = 13 
CharacterFont = 0 
CharacterFontScale = 5 
CharacterLangID = 57 
CharacterLetterspace = 16 
CharacterLocalizeFont = 53 
CharacterOverline = 9 
CharacterPos = 4 
CharacterRTLText = 14 
CharacterSize = 7 
CharacterStrikethru = 10 
CharacterStyle = 2 
CharacterUseVertical = 15 
CnnctAutoGen = 5 
CnnctA = 2 
CnnctB = 3 
CnnctC = 4 
CnnctDirX = 2 
CnnctDirY = 3 
CnnctD = 5 
CnnctType = 4 
CnnctX = 0 
CnnctY = 1 
Comment = 16 
CompNoFill = 0 
CompNoLine = 1 
CompNoShow = 2 
CompNoSnap = 3 
CompPath = 4 
ControlX = 2 
ControlY = 3 
Copyright = 1 
CtlGlue = 6 
CtlTip = 8 
CtlXCon = 4 
CtlXDyn = 2 
CtlX = 0 
CtlYCon = 5 
CtlYDyn = 3 
CtlY = 1 
CustPropsAsk = 7 
CustPropsCalendar = 15 
CustPropsFormat = 3 
CustPropsInvis = 6 
CustPropsLabel = 2 
CustPropsLangID = 14 
CustPropsPrompt = 1 
CustPropsSortKey = 4 
CustPropsType = 5 
CustPropsValue = 0 
DocAddMarkup = 3 
DocLangID = 19 
DocLockPreview = 1 
DocOutputFormat = 0 
DocPreviewQuality = 9 
DocPreviewScope = 10 
DocViewMarkup = 4 
DropSource = 17 
DynFeedback = 8 
EccentricityAngle = 4 
EllipseCenterX = 0 
EllipseCenterY = 1 
EllipseMajorX = 2 
EllipseMajorY = 3 
EllipseMinorX = 4 
EllipseMinorY = 5 
EndTrigger = 12 
EvtCellDblClick = 2 
EvtCellDrop = 4 
EvtCellMultiDrop = 22 
EvtCellTheText = 1 
EvtCellXFMod = 3 
FieldCalendar = 7 
FieldCell = 0 
FieldEditMode = 1 
FieldFormat = 2 
FieldObjectKind = 10 
FieldType = 3 
FieldUICategory = 4 
FieldUICode = 5 
FieldUIFormat = 6 
FillBkgndTrans = 7 
FillBkgnd = 1 
FillForegndTrans = 6 
FillForegnd = 0 
FillPattern = 2 
FillShdwBkgndTrans = 9 
FillShdwBkgnd = 4 
FillShdwForegndTrans = 8 
FillShdwForegnd = 3 
FillShdwObliqueAngle = 13 
FillShdwOffsetX = 11 
FillShdwOffsetY = 12 
FillShdwPattern = 5 
FillShdwScaleFactor = 14 
FillShdwType = 10 
Flags = 13 
FrgnImgHeight = 3 
FrgnImgOffsetX = 0 
FrgnImgOffsetY = 1 
FrgnImgWidth = 2 
GlueType = 9 
GroupDisplayMode = 1 
GroupDontMoveChildren = 5 
GroupIsDropTarget = 2 
GroupIsSnapTarget = 3 
GroupIsTextEditTarget = 4 
GroupSelectMode = 0 
HideText = 5 
HLinkAddress = 1 
HLinkDefault = 7 
HLinkDescription = 0 
HLinkExtraInfo = 3 
HLinkFrame = 4 
HLinkInvisible = 8 
HLinkNewWin = 5 
HLinkSortKey = 15 
HLinkSubAddress = 2 
HorzAlign = 6 
ImageBlur = 4 
ImageBrightness = 2 
ImageContrast = 1 
ImageDenoise = 5 
ImageGamma = 0 
ImageSharpen = 3 
ImageTransparency = 6 
IndentFirst = 0 
IndentLeft = 1 
IndentRight = 2 
InfiniteLineX1 = 0 
InfiniteLineX2 = 2 
InfiniteLineY1 = 1 
InfiniteLineY2 = 3 
LayerActive = 6 
LayerColorTrans = 11 
LayerColor = 2 
LayerGlue = 9 
LayerLock = 7 
LayerMember = 0 
LayerNameUniv = 10 
LayerName = 0 
LayerPrint = 5 
LayerSnap = 8 
LayerStatus = 3 
Layervisible = 4 
LineBeginArrowSize = 8 
LineBeginArrow = 5 
LineColorTrans = 9 
LineColor = 1 
LineEndArrowSize = 4 
LineEndArrow = 6 
LineEndCap = 7 
LinePattern = 2 
LineRounding = 3 
LineWeight = 0 
LocalizeBulletFont = 10 
LockAspect = 4 
LockBegin = 6 
LockCalcWH = 14 
LockCrop = 9 
LockCustProp = 16 
LockDelete = 5 
LockEnd = 7 
LockFormat = 12 
LockFromGroupFormat = 17 
LockGroup = 13 
LockHeight = 1 
LockMoveX = 2 
LockMoveY = 3 
LockRotate = 8 
LockSelect = 15 
LockTextEdit = 11 
LockThemeColors = 18 
LockThemeEffects = 19 
LockVtxEdit = 10 
LockWidth = 0 
LOFlags = 13 
NoAlignBox = 3 
NoCtlHandles = 2 
NoLiveDynamics = 18 
NonPrinting = 1 
NoObjHandles = 0 
NURBSData = 6 
NURBSKnotPrev = 4 
NURBSKnot = 2 
NURBSWeightPrev = 5 
NURBSWeight = 3 
ObjCalendar = 25 
ObjDropOnPageScale = 28 
ObjHelp = 0 
ObjKeywords = 27 
ObjLangID = 26 
ObjLocalizeMerge = 19 
ObjTheme = 29 
PageDrawingScale = 5 
PageDrawScaleType = 7 
PageDrawSizeType = 6 
PageHeight = 1 
PageInhibitSnap = 26 
PageScale = 4 
PageShdwObliqueAngle = 36 
PageShdwOffsetX = 2 
PageShdwOffsetY = 3 
PageShdwScaleFactor = 37 
PageShdwType = 35 
PageUIVisibility = 34 
PageWidth = 0 
PLOAvenueSizeX = 20 
PLOAvenueSizeY = 21 
PLOBlockSizeX = 18 
PLOBlockSizeY = 19 
PLOCtrlAsInput = 3 
PLODynamicsOff = 2 
PLOEnableGrid = 1 
PLOJumpCode = 12 
PLOJumpDirX = 14 
PLOJumpDirY = 15 
PLOJumpFactorX = 24 
PLOJumpFactorY = 25 
PLOJumpStyle = 13 
PLOLineAdjustFrom = 26 
PLOLineAdjustTo = 27 
PLOLineRouteExt = 29 
PLOLineToLineX = 22 
PLOLineToLineY = 23 
PLOLineToNodeX = 16 
PLOLineToNodeY = 17 
PLOPlaceDepth = 10 
PLOPlaceFlip = 28 
PLOPlaceStyle = 8 
PLOPlowCode = 11 
PLOResizePage = 0 
PLORouteStyle = 9 
PLOSplit = 30 
PolylineData = 2 
PrintPropertiesBottomMargin = 3 
PrintPropertiesCenterX = 8 
PrintPropertiesCenterY = 9 
PrintPropertiesLeftMargin = 0 
PrintPropertiesOnPage = 10 
PrintPropertiesPageOrientation = 16 
PrintPropertiesPagesX = 6 
PrintPropertiesPagesY = 7 
PrintPropertiesPaperKind = 17 
PrintPropertiesPaperSource = 18 
PrintPropertiesPrintGrid = 11 
PrintPropertiesRightMargin = 1 
PrintPropertiesScaleX = 4 
PrintPropertiesScaleY = 5 
PrintPropertiesTopMargin = 2 
ReviewerColor = 2 
ReviewerCurrentIndex = 4 
ReviewerInitials = 1 
ReviewerName = 0 
ReviewerReviewerID = 3 
ScratchA = 2 
ScratchB = 3 
ScratchC = 4 
ScratchD = 5 
ScratchX = 0 
ScratchY = 1 
SLOConFixedCode = 12 
SLOFixedCode = 8 
SLOJumpCode = 13 
SLOJumpDirX = 16 
SLOJumpDirY = 17 
SLOJumpStyle = 14 
SLOLineRouteExt = 19 
SLOPermeablePlace = 2 
SLOPermX = 0 
SLOPermY = 1 
SLOPlaceFlip = 18 
SLOPlaceStyle = 11 
SLOPlowCode = 9 
SLORouteStyle = 10 
SLOSplittable = 21 
SLOSplit = 20 
SmartTagButtonFace = 6 
SmartTagDescription = 15 
SmartTagDisabled = 7 
SmartTagDisplayMode = 5 
SmartTagName = 2 
SmartTagXJustify = 3 
SmartTagX = 0 
SmartTagYJustify = 4 
SmartTagY = 1 
SpaceAfter = 5 
SpaceBefore = 4 
SpaceLine = 3 
SplineDegree = 5 
SplineKnot2 = 3 
SplineKnot3 = 4 
SplineKnot = 2 
StyleHidden = 3 
StyleIncludesFill = 1 
StyleIncludesLine = 0 
StyleIncludesText = 2 
TabAlign = 2 
TabPos = 1 
TabStopCount = 0 
TextPosAfterBullet = 12 
TxtBlkBkgndTrans = 11 
TxtBlkBkgnd = 5 
TxtBlkBottomMargin = 3 
TxtBlkDefaultTabStop = 6 
TxtBlkDirection = 10 
TxtBlkLeftMargin = 0 
TxtBlkRightMargin = 1 
TxtBlkTopMargin = 2 
TxtBlkVerticalAlign = 4 
UpdateAlignBox = 4 
UserPrompt = 1 
UserValue = 0 
WalkPref = 10 
XFormAngle = 6 
XFormFlipX = 7 
XFormFlipY = 8 
XFormHeight = 3 
XFormLocPinX = 4 
XFormLocPinY = 5 
XFormPinX = 0 
XFormPinY = 1 
XFormResizeMode = 9 
XFormWidth = 2 
XGridDensity = 6 
XGridOrigin = 10 
XGridSpacing = 8 
XRulerDensity = 0 
XRulerOrigin = 4 
X = 0 
YGridDensity = 7 
YGridOrigin = 11 
YGridSpacing = 9 
YRulerDensity = 1 
YRulerOrigin = 5 
Y = 1 
#End Enum 
 
#Public Enum VisCellVals 
Architectural = 1 
ArrowSizeColossal = 6 
ArrowSizeJumbo = 5 
ArrowSizeLarge = 3 
ArrowSizeMedium = 2 
ArrowSizeSmall = 1 
ArrowSizeVeryLarge = 4 
ArrowSizeVerySmall = 0 
BackDotsMini = 8 
BackDotsWide = 18 
Bold = 1 
CalArabicHijri = 1 
CalChineseTaiwan = 3 
CalHebrewLunar = 2 
CalJapaneseEmperor = 4 
CalKoreanDanki = 6 
CalSakaEra = 7 
CalThaiBuddhist = 5 
CalTranslitEnglish = 8 
CalTranslitFrench = 9 
CalWestern = 0 
CaseAllCaps = 1 
CaseInitialCaps = 2 
CaseNormal = 0 
CnnctTypeInwardOutward = 2 
CnnctTypeInward = 0 
CnnctTypeOutward = 1 
ComplexBold = 16 
ComplexItalic = 32 
CtlLockedHidden = 6 
CtlLocked = 1 
CtlOffsetMaxHidden = 9 
CtlOffsetMax = 4 
CtlOffsetMidHidden = 8 
CtlOffsetMid = 3 
CtlOffsetMinHidden = 7 
CtlOffsetMin = 2 
CtlProportionalHidden = 5 
CtlProportional = 0 
Custom = 3 
DocPreviewQualityDetailed = 1 
DocPreviewQualityDraft = 0 
DocPreviewScope1stPage = 0 
DocPreviewScopeNone = 1 
DSArch = 7 
DSEngr = 6 
DSMetric = 5 
DynFBDefault = 0 
DynFBUCon3Leg = 1 
DynFBUCon5Leg = 2 
Engineering = 2 
ForeDotsMini = 10 
ForeDotsNarrow = 11 
ForeDotsWide = 12 
FSTOblique = 2 
FSTPageDefault = 0 
FSTSimple = 1 
GlueTypeDefault = 0 
GlueTypeNoWalkingTo = 8 
GlueTypeNoWalking = 4 
GlueTypeWalking = 2 
GridCoarse = 2 
GridFine = 8 
GridFixed = 0 
GridNormal = 4 
GrpDispModeBack = 1 
GrpDispModeFront = 2 
GrpDispModeNone = 0 
GrpSelModeGroup1st = 1 
GrpSelModeGroupOnly = 0 
GrpSelModeMembers1st = 2 
HalfAndHalf = 9 
HorzCenter = 1 
HorzDistribute = 4 
HorzJustifyHigh = 8 
HorzJustifyLow = 6 
HorzJustifyMedium = 7 
HorzJustify = 3 
HorzLeft = 0 
HorzRight = 2 
Italic = 2 
LayerAvailable = 2 
LayerDeleted = 1 
LayerValid = 0 
LocFontAlways = 1 
LocFontIfArialOrSym = 0 
LocFontNever = 2 
LOFlagsDont = 4 
LOFlagsPlacable = 1 
LOFlagsPNRGroup = 8 
LOFlagsRoutable = 2 
LOFlagsVisDecides = 0 
LOFlipDefault = 0 
LOFlipNone = 8 
LOFlipRotate = 4 
LOFlipX = 1 
LOFlipY = 2 
Logical = 4 
LOJumpDirXDefault = 0 
LOJumpDirXDown = 2 
LOJumpDirXUp = 1 
LOJumpDirYDefault = 0 
LOJumpDirYLeft = 1 
LOJumpDirYRight = 2 
LOJumpStyle2Point = 5 
LOJumpStyle3Point = 6 
LOJumpStyle4Point = 7 
LOJumpStyle5Point = 8 
LOJumpStyle6Point = 9 
LOJumpStyleArc = 1 
LOJumpStyleDefault = 0 
LOJumpStyleGap = 2 
LOJumpStyleSquare = 3 
LOJumpStyleTriangle = 4 
LOPlaceBottomToTop = 4 
LOPlaceCircular = 6 
LOPlaceCompactDownLeft = 14 
LOPlaceCompactDownRight = 7 
LOPlaceCompactLeftDown = 13 
LOPlaceCompactLeftUp = 12 
LOPlaceCompactRightDown = 8 
LOPlaceCompactRightUp = 9 
LOPlaceCompactUpLeft = 11 
LOPlaceCompactUpRight = 10 
LOPlaceDefault = 0 
LOPlaceHierarchyBottomToTopCenter = 20 
LOPlaceHierarchyBottomToTopLeft = 19 
LOPlaceHierarchyBottomToTopRight = 21 
LOPlaceHierarchyLeftToRightBottom = 24 
LOPlaceHierarchyLeftToRightMiddle = 23 
LOPlaceHierarchyLeftToRightTop = 22 
LOPlaceHierarchyRightToLeftBottom = 27 
LOPlaceHierarchyRightToLeftMiddle = 26 
LOPlaceHierarchyRightToLeftTop = 25 
LOPlaceHierarchyTopToBottomCenter = 17 
LOPlaceHierarchyTopToBottomLeft = 16 
LOPlaceHierarchyTopToBottomRight = 18 
LOPlaceLeftToRight = 2 
LOPlaceParentDefault = 15 
LOPlaceRadial = 3 
LOPlaceRightToLeft = 5 
LOPlaceTopToBottom = 1 
LORouteCenterToCenter = 16 
LORouteDefault = 0 
LORouteExtDefault = 0 
LORouteExtNURBS = 2 
LORouteExtStraight = 1 
LORouteFlowchartEW = 13 
LORouteFlowchartNS = 5 
LORouteFlowchartSN = 12 
LORouteFlowchartWE = 6 
LORouteNetwork = 9 
LORouteOrgChartEW = 11 
LORouteOrgChartNS = 3 
LORouteOrgChartSN = 10 
LORouteOrgChartWE = 4 
LORouteRightAngle = 1 
LORouteSimpleEW = 20 
LORouteSimpleHV = 21 
LORouteSimpleNS = 17 
LORouteSimpleSN = 19 
LORouteSimpleVH = 22 
LORouteSimpleWE = 18 
LORouteStraight = 2 
LORouteTreeEW = 15 
LORouteTreeNS = 7 
LORouteTreeSN = 14 
LORouteTreeWE = 8 
NoFill = 0 
NoLayerColor = 255 
NoScale = 0 
PLOJumpDisplayOrder = 4 
PLOJumpHorizontal = 1 
PLOJumpLastRouted = 3 
PLOJumpNone = 0 
PLOJumpProhibitAll = 6 
PLOJumpReverseDisplayOrder = 5 
PLOJumpVertical = 2 
PLOLineAdjustFromAll = 1 
PLOLineAdjustFromNone = 2 
PLOLineAdjustFromNotRelated = 0 
PLOLineAdjustFromRoutingDefault = 3 
PLOLineAdjustToAll = 1 
PLOLineAdjustToDefault = 0 
PLOLineAdjustToNone = 2 
PLOLineAdjustToRelated = 3 
PLOPlaceBottomToTop = 4 
PLOPlaceCircular = 6 
PLOPlaceCompactDownLeft = 14 
PLOPlaceCompactDownRight = 7 
PLOPlaceCompactLeftDown = 13 
PLOPlaceCompactLeftUp = 12 
PLOPlaceCompactRightDown = 8 
PLOPlaceCompactRightUp = 9 
PLOPlaceCompactUpLeft = 11 
PLOPlaceCompactUpRight = 10 
PLOPlaceDefault = 0 
PLOPlaceDepthDeep = 2 
PLOPlaceDepthDefault = 0 
PLOPlaceDepthMedium = 1 
PLOPlaceDepthShallow = 3 
PLOPlaceLeftToRight = 2 
PLOPlaceRadial = 3 
PLOPlaceRightToLeft = 5 
PLOPlaceTopToBottom = 1 
PLOPlowAll = 1 
PLOPlowNone = 0 
PLOSplitAllow = 1 
PLOSplitNone = 0 
PosNormal = 0 
PosSub = 2 
PosSuper = 1 
PPFlagsRTLText = 1 
PPOLandscape = 2 
PPOPortrait = 1 
PPOSameAsPrinter = 0 
PrintSetup = 0 
PropTypeBool = 3 
PropTypeCurrency = 7 
PropTypeDate = 5 
PropTypeDuration = 6 
PropTypeListFix = 1 
PropTypeListVar = 4 
PropTypeNumber = 2 
PropTypeString = 0 
RulerCoarse = 8 
RulerFine = 32 
RulerFixed = 0 
RulerNormal = 16 
ScaleCustom = 3 
ScaleMechanical = 5 
ScaleMetric = 4 
SLOConFixedRerouteAsNeeded = 1 
SLOConFixedRerouteFreely = 0 
SLOConFixedRerouteNever = 2 
SLOConFixedRerouteOnCrossover = 3 
SLOFixedConnPtsIgnore = 32 
SLOFixedConnPtsOnly = 64 
SLOFixedNoFoldToShape = 128 
SLOFixedPermeablePlow = 4 
SLOFixedPlacement = 1 
SLOFixedPlow = 2 
SLOJumpAlways = 2 
SLOJumpDefault = 0 
SLOJumpNeither = 4 
SLOJumpNever = 1 
SLOJumpOther = 3 
SLOPlowAlways = 2 
SLOPlowDefault = 0 
SLOPlowNever = 1 
SLOSplitAllow = 1 
SLOSplitNone = 0 
SLOSplittableAllow = 1 
SLOSplittableNone = 0 
SmallCaps = 8 
SmartTagDispModeAlways = 2 
SmartTagDispModeMouseOver = 0 
SmartTagDispModeShapeSelected = 1 
SmartTagXJustifyCenter = 1 
SmartTagXJustifyLeft = 0 
SmartTagXJustifyRight = 2 
SmartTagYJustifyBottom = 2 
SmartTagYJustifyMiddle = 1 
SmartTagYJustifyTop = 0 
Solid = 1 
Standard = 2 
TabStopCenter = 1 
TabStopComma = 4 
TabStopDecimal = 3 
TabStopLeft = 0 
TabStopRight = 2 
TFOKHorizontalInVertical = 1 
TFOKStandard = 0 
ThickDiagonalCross = 17 
ThickDownDiagonal = 15 
ThickHorz = 13 
ThickUpDiagonal = 16 
ThickVertical = 14 
ThinCross = 23 
ThinDiagonalCross = 24 
ThinDownDiagonal = 21 
ThinHorz = 19 
ThinUpDiagonal = 22 
ThinVert = 20 
Tight = 1 
TxtBlkFlagsHideHiddens = 1 
TxtBlkLeftToRight = 0 
TxtBlkOpaque = 255 
TxtBlkTopToBottom = 1 
UIVHidden = 1 
UIVNormal = 0 
UnderLine = 4 
VertBottom = 2 
VertMiddle = 1 
VertTop = 0 
WalkPrefBegNS = 1 
WalkPrefEndNS = 2 
WideCross = 3 
WideDiagonalCross = 4 
WideDownDiagonal = 5 
WideHorz = 6 
WideUpDiagonal = 2 
WideVert = 7 
XFormResizeDontCare = 0 
XFormResizeScale = 2 
XFormResizeSpread = 1 
#End Enum 
 
#Public Enum visCharsBias 
BiasLeft = 1 
BiasLetVisioChoose = 0 
BiasRight = 2 
#End Enum 
 
#Public Enum VisCutCopyPasteCodes 
CopyPasteNormal = 0x0 
CopyPasteNoTranslate = 0x1 
#End Enum 
 
#Public Enum VisDataColumnProperties 
DataColumnPropertyCalendar = 3 
DataColumnPropertyCurrency = 5 
DataColumnPropertyDisplayName = 6 
DataColumnPropertyHyperlink = 8 
DataColumnPropertyLangID = 2 
DataColumnPropertyType = 1 
DataColumnPropertyUnits = 4 
DataColumnPropertyVisible = 7 
#End Enum 
 
#Public Enum VisDataRecordsetAddOptions 
DataRecordsetNoExternalDataUI = 1 
DataRecordsetNoRefreshUI = 2 
DataRecordsetNoAdvConfig = 4 
DataRecordsetDelayQuery = 8 
DataRecordsetDontCopyLinks = 16 
#End Enum 
 
#Public Enum visDefaultColors 
Black = 0 
Blue = 4 
Cyan = 7 
DarkBlue = 10 
DarkCyan = 13 
DarkGray = 19 
DarkGreen = 9 
DarkRed = 8 
DarkYellow = 11 
Gray10 = 15 
Gray20 = 16 
Gray30 = 17 
Gray40 = 18 
Gray50 = 19 
Gray60 = 20 
Gray70 = 21 
Gray80 = 22 
Gray90 = 23 
Gray = 14 
Green = 3 
Magenta = 6 
Purple = 12 
Red = 2 
Transparent = 0 
White = 1 
Yellow = 5 
#End Enum 
 
#Public Enum VisDefaultSaveFormat 
DefaultSaveCurrentBinary = 0 
DefaultSaveCurrentXML = 2 
DefaultSavePreviousBinary = 1 
#End Enum 
 
#Public Enum visDistributeTypes 
DistHorzCenter = 2 
DistHorzLeft = 1 
DistHorzRight = 3 
DistHorzSpace = 0 
DistVertBottom = 7 
DistVertMiddle = 6 
DistVertSpace = 4 
DistVertTop = 5 
#End Enum 
 
#Public Enum VisDocCleanActions 
DocCleanActAll = 0x3FFF 
DocCleanActBadDisplayLists = 0x100 
DocCleanActBadFieldFormulas = 0x800 
DocCleanActBadFieldMarks = 0x1000 
DocCleanActBadReferences = 0x2000 
DocCleanActConstantFormulas = 0x20 
DocCleanActDefault = 0x1FD8 
DocCleanActDeletedFields = 0x400 
DocCleanActDuplicateSubs = 0x80 
DocCleanActEmptyRowsAndSects = 0x2 
DocCleanActLocalFormulas = 0x1 
DocCleanActMissingSubs = 0x10 
DocCleanActNearZero = 0x40 
DocCleanActNonDefaultFonts = 0x4 
DocCleanActStaleResults = 0x8 
DocCleanAlertDefault = 0x0 
DocCleanFixDefault = 0x3D8 
#End Enum 
 
#Public Enum VisDocCleanTargets 
DocCleanTargAll = 0xFF 
DocCleanTargBPages = 0x2 
DocCleanTargDoc = 0x10 
DocCleanTargFPages = 0x1 
DocCleanTargMasters = 0x4 
DocCleanTargPageSheet = 0x100 
DocCleanTargStyles = 0x8 
#End Enum 
 
#Public Enum VisDocExIntent 
DocExIntentPrint = 1 
DocExIntentScreen = 0 
#End Enum 
 
#Public Enum VisDocModeArgs 
DocModeDesign = 1 
DocModeRun = 0 
InvalDocID = -1 
#End Enum 
 
#Public Enum VisDocumentTypes 
DocTypeInval = 0 
TypeDrawing = 1 
TypeStencil = 2 
TypeTemplate = 3 
#End Enum 
 
#Public Enum VisDocVersions 
Version100 = 393216 
Version10 = 65571 
Version110 = 720896 #(0xB0000) 
Version120 = 720896 #(0xB0000) 
Version20 = 131072 #(0x20000) 
Version30 = 196611 #(0x30003) 
Version40 = 262144 #(0x40000) 
Version50 = 327680 #(0x50000) 
Version60 = 393216 #(0x60000) 
VersionUnsaved = 0 
#End Enum 
 
#Public Enum VisDrawRegionFlags 
DrawRegionDeleteInput = 0x4 
DrawRegionIgnorevisible = 0x20 
DrawRegionIncludeDataGraphics = 0x40 
DrawRegionIncludeHidden = 0x10 
#End Enum 
 
#Public Enum VisDrawSplineFlags 
Polyarcs = 256 
Polyline1D = 8 
Spline1D = 8 
SplineAbrupt = 4 
SplineDoCircles = 2 
SplinePeriodic = 1 
#End Enum 
 
#Public Enum VisEventCodes 
ActCodeAdvise = 2 
ActCodeRunAddon = 1 
EvtAdd = 32768 
EvtAfterModal = 64 
EvtApp = 4096 
EvtAppActivate = 1 
EvtAppDeactivate = 2 
EvtBeforeModal = 32 
EvtBeforeQuit = 16 
EvtCell = 2048 
EvtCodeAfterForcedFlush = 201 
EvtCodeAfterResume = 209 
EvtCodeAfterResumeEvents = 213 
EvtCodeBefDocSaveAs = 8 
EvtCodeBefDocSave = 7 
EvtCodeBefForcedFlush = 200 
EvtCodeBeforeSuspend = 208 
EvtCodeBeforeSuspendEvents = 212 
EvtCodeBefSelDel = 901 
EvtCodeBefWinPageTurn = 703 
EvtCodeBefWinSelDel = 702 
EvtCodeCancelConvertToGroup = 908 
EvtCodeCancelDocClose = 10 
EvtCodeCancelMasterDel = 401 
EvtCodeCancelPageDel = 501 
EvtCodeCancelQuit = 205 
EvtCodeCancelSelDel = 904 
EvtCodeCancelSelGroup = 910 
EvtCodeCancelStyleDel = 301 
EvtCodeCancelSuspend = 207 
EvtCodeCancelSuspendEvents = 211 
EvtCodeCancelUngroup = 906 
EvtCodeCancelWinClose = 707 
EvtCodeDocCreate = 1 
EvtCodeDocDesign = 6 
EvtCodeDocOpen = 2 
EvtCodeDocRunning = 5 
EvtCodeDocSaveAs = 4 
EvtCodeDocSave = 3 
EvtCodeEnterScope = 202 
EvtCodeExitScope = 203 
EvtCodeInval = 0 
EvtCodeKeyDown = 712 
EvtCodeKeyPress = 713 
EvtCodeKeyUp = 714 
EvtCodeMouseDown = 709 
EvtCodeMouseMove = 710 
EvtCodeMouseUp = 711 
EvtCodeQueryCancelConvertToGroup = 907 
EvtCodeQueryCancelDocClose = 9 
EvtCodeQueryCancelMasterDel = 400 
EvtCodeQueryCancelPageDel = 500 
EvtCodeQueryCancelQuit = 204 
EvtCodeQueryCancelSelDel = 903 
EvtCodeQueryCancelSelGroup = 909 
EvtCodeQueryCancelStyleDel = 300 
EvtCodeQueryCancelSuspend = 206 
EvtCodeQueryCancelSuspendEvents = 210 
EvtCodeQueryCancelUngroup = 905 
EvtCodeQueryCancelWinClose = 706 
EvtCodeSelAdded = 902 
EvtCodeShapeBeforeTextEdit = 803 
EvtCodeShapeDelete = 801 
EvtCodeShapeExitTextEdit = 804 
EvtCodeShapeParentChange = 802 
EvtCodeViewChanged = 705 
EvtCodeWinOnAddonKeyMSG = 708 
EvtCodeWinPageTurn = 704 
EvtCodeWinSelChange = 701 
EvtConnect = 256 
EvtDel = 16384 
EvtDataRecordset = 32 
EvtDoc = 2 
EvtFormula = 4096 
EvtIDInval = -1 
EvtIdle = 1024 
EvtIdMostRecent = 0 
EvtMarker = 256 
EvtMaster = 8 
EvtMod = 8192 
EvtNonePending = 512 
EvtObjActivate = 4 
EvtObjDeactivate = 8 
EvtPage = 16 
EvtRemoveHiddenInformation = 11 
EvtRow = 1024 
EvtSection = 512 
EvtShape = 64 
EvtShapeDataGraphicChanged = 807 
EvtShapeLinkAdded = 805 
EvtShapeLinkDeleted = 806 
EvtStyle = 4 
EvtText = 128 
EvtWinActivate = 128 
EvtWindow = 1 
ScopeIDInval = -1 
#End Enum 
 
#Public Enum VisExistsFlags 
ExistsAnywhere = 0 
ExistsLocally = 1 
#End Enum 
 
#Public Enum VisFieldCategories 
FCatCustom = 0 
FCatDateTime = 1 
FCatDocument = 2 
FCatGeometry = 3 
FCatObject = 4 
FCatPage = 5 
#End Enum 
 
#Public Enum VisFieldCodes 
FCodeAngle = 2 
FCodeBackgroundName = 0 
FCodeCategory = 9 
FCodeCompany = 8 
FCodeCreateDate = 0 
FCodeCreateTime = 1 
FCodeCreator = 0 
FCodeCurrentDate = 2 
FCodeCurrentTime = 3 
FCodeData1 = 0 
FCodeData2 = 1 
FCodeData3 = 2 
FCodeDescription = 1 
FCodeDirectory = 2 
FCodeEditDate = 4 
FCodeEditTime = 5 
FCodeFileName = 3 
FCodeHeight = 1 
FCodeHyperlinkBase = 10 
FCodeKeyWords = 4 
FCodeManager = 7 
FCodeMasterName = 4 
FCodeNumberOfPages = 2 
FCodeObjectID = 3 
FCodeObjectName = 5 
FCodeObjectType = 6 
FCodePageName = 1 
FCodePageNumber = 3 
FCodePrintDate = 6 
FCodePrintTime = 7 
FCodeSubject = 5 
FCodeTitle = 6 
FCodeWidth = 0 
#End Enum 
 
#Public Enum VisFieldFormats 
Fmt0PlDefUnits = 3 
Fmt0PlNoUnits = 2 
Fmt1PlDefUnits = 5 
Fmt1PlNoUnits = 4 
Fmt2PlDefUnits = 7 
Fmt2PlNoUnits = 6 
Fmt3PlDefUnits = 9 
Fmt3PlNoUnits = 8 
FmtDateDDMMYY = 27 
FmtDateDMMMMYYYY = 29 
FmtDateDMMMYYYY = 28 
FmtDateDMYY = 26 
FmtDategeMMMMddd_K = 62 
FmtDategeMMMMddddww_K = 60 
FmtDategggemd_J = 56 
FmtDategggemdww_J = 54 
FmtDateLong = 21 
FmtDateMDYY = 22 
FmtDateMMDDYY = 23 
FmtDateMmmDYYYY = 24 
FmtDateMmmmDYYYY = 25 
FmtDateTWNfyyyymmdd_C = 53 
FmtDateTWNfYYYYMMDDD_C = 50 
FmtDateTWNfyyyymmddww_C = 52 
FmtDateTWNsYYYYMMDDD_C = 51 
FmtDateShort = 20 
FmtDatewwyyyymd_S = 79 
FmtDatewwyyyymmdd_S = 78 
FmtDateyy_mm_dd = 65 
FmtDateyymmdd = 45 
FmtDateyyyy_m_d = 64 
FmtDateyyyymd_J = 57 
FmtDateyyyymd_K = 63 
FmtDateyyyymd_S = 76 
FmtDateyyyymdww_J = 55 
FmtDateyyyymdww_K = 61 
FmtDateyyyymd = 44 
FmtDateyyyymmdd_S = 77 
FmtDateYYYYMMMDDD_C = 59 
FmtDateYYYYMMMDDDWWW_C = 58 
FmtDegrees = 12 
FmtFeetAndInches1Pl = 13 
FmtFeetAndInches2Pl = 14 
FmtFeetAndInches = 10 
FmtFraction1PlDefUnits = 16 
FmtFraction1PlNoUnits = 15 
FmtFraction2PlDefUnits = 18 
FmtFraction2PlNoUnits = 17 
FmtMsoDateEnglish = 208 
FmtMsoDateISO = 204 
FmtMsoDateLongDay = 201 
FmtMsoDateLong = 202 
FmtMsoDateMon_Yr = 210 
FmtMsoDateMonthYr = 209 
FmtMsoDateShortAbb = 207 
FmtMsoDateShortAlt = 203 
FmtMsoDateShortMon = 205 
FmtMsoDateShortSlash = 206 
FmtMsoDateShort = 200 
FmtMsoFEExtra1 = 217 
FmtMsoFEExtra2 = 218 
FmtMsoFEExtra3 = 219 
FmtMsoFEExtra4 = 220 
FmtMsoFEExtra5 = 221 
FmtMsoTime24 = 215 
FmtMsoTimeDatePM = 211 
FmtMsoTimeDateSecPM = 212 
FmtMsoTimePM = 213 
FmtMsoTimeSec24 = 216 
FmtMsoTimeSecPM = 214 
FmtNumGenDefUnits = 1 
FmtNumGenNoUnits = 0 
FmtRadians = 11 
FmtStrLower = 38 
FmtStrNormal = 37 
FmtStrUpper = 39 
FmtTimeAMPM_hmm_C = 70 
FmtTimeAMPM_hmm_J = 68 
FmtTimeAMPM_hmm_K = 72 
FmtTimeAMPMhhmm_S = 81 
FmtTimeAMPMhmm_C = 66 
FmtTimeAMPMhmm_J = 46 
FmtTimeAMPMhmm_K = 67 
FmtTimeAMPMhmm_S = 80 
FmtTimeGen = 30 
FmtTimeHHMM24 = 34 
FmtTimeHHMMAMPM_E = 75 
FmtTimeHHMMAMPM = 36 
FmtTimeHHMM = 32 
FmtTimehmm_C = 71 
FmtTimehmm_J = 69 
FmtTimehmm_K = 73 
FmtTimeHMM24 = 33 
FmtTimeHMMAMPM_E = 74 
FmtTimeHMMAMPM = 35 
FmtTimeHMM = 31 
#End Enum 
 
#Public Enum VisFilterActions 
FilterMouseMoveDragBegin = 1 
FilterMouseMoveDragDrop = 5 
FilterMouseMoveDragEnter = 2 
FilterMouseMoveDragLeave = 4 
FilterMouseMoveDragOver = 3 
FilterMouseMoveNoDrag = 0 
#End Enum 
 
#Public Enum VisFixedFormatTypes 
FixedFormatPDF = 1 
FixedFormatXPS = 2 
#End Enum 
 
#Public Enum VisFlipDirection 
FlipHorizontal = 1 
FlipVertical = 2 
#End Enum 
 
#Public Enum VisFlipTypes 
FlipSelectionWithPin = 1 
FlipSelection = 0 
FlipShapes = 2 
#End Enum 
 
 
#Public Enum VisFontAttributes 
Font0Alias = 128 
#End Enum 
 
#Public Enum VisFromParts 
BeginX = 7 
BeginY = 8 
Begin = 9 
BottomEdge = 4 
CenterEdge = 2 
ConnectFromError = -1 
ControlPoint = 100 
EndX = 10 
EndY = 11 
End = 12 
FromAngle = 13 
FromNone = 0 
FromPin = 14 
LeftEdge = 1 
MiddleEdge = 5 
RightEdge = 3 
TopEdge = 6 
#End Enum 
 
#Public Enum VisGeomFlags 
GeomExcludeLastPoint = 1 #(0x1) 
GeomWHPct = 16 #(0x10) 
GeomXYLocal = 32 #(0x20) 
#End Enum 
 
#Public Enum VisGetSetArgs 
GetFloats = 0 
GetFormulasU = 5 
GetFormulas = 4 
GetRoundedInts = 2 
GetStrings = 3 
GetTruncatedInts = 1 
SetBlastGuards = 2 
SetFormulas = 1 
SetTestCircular = 4 
SetUniversalSyntax = 8 
#End Enum 
 
#Public Enum VisGlueSettings 
GlueToConnectionPoints = 0x8 
GlueToDisabled = 0x8000 
GlueToGeometry = 0x20 
GlueToGuides = 0x1 
GlueToHandles = 0x2 
GlueToNone = 0x0 
GlueToVertices = 0x4 
#End Enum 
 
#Public Enum VisGraphicField 
GraphicExpression = 2 
GraphicPropertyLabel = 1 
#End Enum 
 
#Public Enum VisGraphicItemTypes 
TypeIconSet = 2 
TypeTextCallout = 3 
TypeDataBar = 4 
TypeColorByValue = 5 
TypeHeading = 6 
#End Enum 
 
#Public Enum VisGraphicPositionHorizontal 
GraphicFarLeft = 0 
GraphicLeftEdge = 1 
GraphicLeft = 2 
GraphicCenter = 3 
GraphicRight = 4 
GraphicRightEdge = 5 
GraphicFarRight = 6 
#End Enum 
 
#Public Enum VisGraphicPositionVertical 
GraphicBelow = 0 
GraphicBottomEdge = 1 
GraphicBottom = 2 
GraphicMiddle = 3 
GraphicTop = 4 
GraphicTopEdge = 5 
GraphicAbove = 6 
#End Enum 
 
#Public Enum VisGuideTypes 
Horz = 2 
Point = 1 
Vert = 3 
#End Enum 
 
#Public Enum VisHitTestResults 
HitInside = 2 
HitOnBoundary = 1 
HitOutside = 0 
#End Enum 
 
#Public Enum VisHorizontalAlignTypes 
gHorzAlignCenter = 2 
HorzAlignLeft = 1 
HorzAlignNone = 0 
HorzAlignRight = 3 
#End Enum 
 
#Public Enum VisInsertObjArgs 
InsertAsControl = 8192 
InsertAsEmbed = 16384 
InsertDontShow = 4096 
InsertIcon = 16 
InsertLink = 8 
InsertNoDesignModeTransition = 256 
#End Enum 
 
#Public Enum VisKeyButtonFlags 
KeyControl = 8 
KeyShift = 4 
MouseLeft = 1 
MouseMiddle = 16 
MouseRight = 2 
#End Enum 
 
#Public Enum VisLinkReplaceBehavior 
LinkReplaceAlways = 1 
LinkReplaceNever = 0 
LinkReplacePrompt = 2 
#End Enum 
 
#Public Enum VisMasterProperties 
Automatic = 1 
Center = 2 
Double = 4 
IconFormatBMP = 2 
IconFormatVisio = 0 
Left = 1 
Manual = 0 
MasFPCenter = 4096 
MasFPScale = 16384 
MasFPStretch = 8192 
MasFPTile = 0 
MasIsFillPat = 4 
MasIsLineEnd = 2 
MasIsLinePat = 1 
MasLEDefault = 0 
MasLEScale = 1024 
MasLEUpright = 256 
MasLPAnnotate = 48 
MasLPScale = 64 
MasLPStretch = 32 
MasLPTileDeform = 0 
MasLPTile = 16 
Normal = 1 
Right = 3 
Tall = 2 
Wide = 3 
#End Enum 
 
#Public Enum VisMasterTypes 
TypeDataGraphic = 5 
TypeFillPattern = 2 
TypeLineEnd = 4 
TypeLinePattern = 3 
TypeMaster = 1 
TypeThemeColors = 6 
TypeThemeEffects = 7 
#End Enum 
 
#Public Enum VisMeasurementSystem 
MSDefault = 0 
MSMetric = 1 
MSUS = 2 
#End Enum 
 
#Public Enum VisMouseMoveDragStates 
MouseMoveDragStatesBegin = 1 
MouseMoveDragStatesDrop = 5 
MouseMoveDragStatesEnter = 2 
MouseMoveDragStatesLeave = 4 
MouseMoveDragStatesNone = 0 
MouseMoveDragStatesOver = 3 
#End Enum 
 
#Public Enum VisObjectTypes 
ObjTypeAddon = 31 
ObjTypeAddons = 32 
ObjTypeApplicationSettings = 51 
ObjTypeApp = 3 
ObjTypeCell = 4 
ObjTypeChars = 5 
ObjTypeColor = 29 
ObjTypeColors = 30 
ObjTypeConnect = 8 
ObjTypeConnects = 9 
ObjTypeCurve = 42 
ObjTypeDataColumn = 56 
ObjTypeDataColumns = 55 
ObjTypeDataConnection = 54 
ObjTypeDataRecordset = 53 
ObjTypeDataRecordsetChangedEvent = 57 
ObjTypeDataRecordsets = 52 
ObjTypeDoc = 10 
ObjTypeDocs = 11 
ObjTypeEventList = 34 
ObjTypeEvent = 33 
ObjTypeFont = 27 
ObjTypeFonts = 28 
ObjTypeGlobal = 36 
ObjTypeGraphicItem = 59 
ObjTypeGraphicItems = 58 
ObjTypeHyperlink = 37 
ObjTypeHyperlinks = 43 
ObjTypeKeyboardEvent = 50 
ObjTypeLayer = 25 
ObjTypeLayers = 26 
ObjTypeMasterShortcut = 47 
ObjTypeMasterShortcuts = 46 
ObjTypeMaster = 12 
ObjTypeMasters = 13 
ObjTypeMouseEvent = 49 
ObjTypeMSGWrap = 48 
ObjTypeOLEObject = 39 
ObjTypeOLEObjects = 38 
ObjTypePage = 14 
ObjTypePages = 15 
ObjTypePath = 41 
ObjTypePaths = 40 
ObjTypeRow = 45 
ObjTypeSection = 44 
ObjTypeSelection = 16 
ObjTypeShape = 17 
ObjTypeShapes = 18 
ObjTypeStyle = 19 
ObjTypeStyles = 20 
ObjTypeUnknown = 1 
ObjTypeWindow = 21 
ObjTypeWindows = 22 
#End Enum 
 
#Public Enum VisOnComponentEnterCodes 
ComponentStateModal = 1 
ModalDeferEvents = 0x10000 
ModalDisableVisiosFrame = 0x80000 
ModalDontBlockMessages = 0x40000 
ModalNoBeforeAfter = 0x20000 
#End Enum 
 
#Public Enum VisOpenSaveArgs 
AddDocked = 4 
AddHidden = 64 
AddMacrosDisabled = 128 
AddMinimized = 16 
AddNoWorkspace = 256 
AddStencil = 512 
OpenCopy = 1 
OpenDocked = 4 
OpenDontList = 8 
OpenHidden = 64 
OpenMacrosDisabled = 128 
OpenMinimized = 16 
OpenNoWorkspace = 256 
OpenRO = 2 
OpenRW = 32 
SaveAsListInMRU = 4 
SaveAsRO = 1 
SaveAsWS = 2 
#End Enum 
 
#Public Enum VisPageAndMasterIDs 
InvalMasterID = -1 
InvalPageID = -1 
#End Enum 
 
#Public Enum VisPageSizingBehaviors 
NeverResizePages = 0 
ResizePages = 1 
#End Enum 
 
#Public Enum VisPageTypes 
PageTypeInval = 0 
TypeBackground = 2 
TypeForeground = 1 
TypeMarkup = 3 
#End Enum 
 
#Public Enum VisPaperSizes 
PaperSizeA3 = 8 
PaperSizeA4 = 9 
PaperSizeA5 = 11 
PaperSizeB4 = 12 
PaperSizeB5 = 13 
PaperSizeFolio = 14 
PaperSizeLegal = 5 
PaperSizeLetter = 1 
PaperSizeNote = 18 
PaperSizeSizeC = 24 
PaperSizeSizeD = 25 
PaperSizeSizeE = 26 
PaperSizeUnknown = 0 
#End Enum 
 
#Public Enum VisPasteSpecialCodes 
PasteBitmap = 2 
PasteDIB = 8 
PasteEMF = 14 
PasteHyperlink = 65538 
PasteInk = 65544 
PasteMetafile = 3 
PasteOEMText = 7 
PasteOLEObject = 65536 
PasteRichText = 65537 
PasteText = 1 
PasteURL = 65539 
PasteVisioIcon = 65543 
PasteVisioMastersXML = 65546 
PasteVisioMasters = 65541 
PasteVisioShapesXML = 65545 
PasteVisioShapesWithoutDataLinks = 65548 
PasteVisioShapes = 65540 
PasteVisioText = 65542 
#End Enum 
 
#Public Enum VisPrimaryKeySettings 
KeyComposite = 3 
KeyRowOrder = 1 
KeySingle = 2 
#End Enum 
 
#Public Enum VisPrintOutRange 
PrintAll = 0 
PrintCurrentPage = 2 
PrintCurrentView = 4 
PrintFromTo = 1 
PrintSelection = 3 
#End Enum 
 
#Public Enum VisProtection 
ProtectBackgrounds = 0x8 
ProtectMasters = 0x4 
ProtectNone = 0x0 
ProtectPreviews = 0x10 
ProtectShapes = 0x2 
ProtectStyles = 0x1 
#End Enum 
 
#Public Enum VisRefreshSettings 
RefreshNoReconcilationUI = 2 
RefreshOverwriteAll = 1 
#End Enum 
 
#Public Enum VisRegionalUIOptions 
RegionalUIOptionsHide = 0 
RegionalUIOptionsShow = 1 
RegionalUIOptionsUseSystemSettings = -1 
#End Enum 
 
#Public Enum VisRemoveHiddenInfoItems 
RHIPersonalInfo = 1 
RHIDataQuery = 2 
RHIDataRecordsets = 4 
RHIPreview = 8 
RHIMasters = 16 
RHIStyles = 32 
RHIDataRows = 64 
#End Enum 
 
#Public Enum VisRotationTypes 
RotateSelectionWithPin = 1 
RotateSelection = 0 
RotateShapes = 2 
#End Enum 
 
#Public Enum VisRoundFlags 
Round = 1 
Truncate = 0 
#End Enum 
 
#Public Enum VisRowIndices 
Row1stHyperlink = 0 
RowAction = 0 
RowAlign = 14 
RowAnnotation = 0 
RowCharacter = 0 
RowComponent = 0 
RowConnectionPts = 0 
RowControl = 0 
RowDoc = 20 
RowEvent = 5 
RowField = 0 
RowFill = 3 
RowFirst = 0 
RowForeign = 9 
RowGroup = 22 
RowHelpCopyright = 16 
RowImage = 21 
RowInval = -1 
RowLast = -2 
RowLayerMem = 6 
RowLayer = 0 
RowLine = 2 
RowLock = 15 
RowMisc = 17 
RowNone = -1 
RowPageLayout = 24 
RowPage = 10 
RowParagraph = 0 
RowPrintProperties = 25 
RowProp = 0 
RowReviewer = 0 
RowRulerGrid = 18 
RowScratch = 0 
RowShapeLayout = 23 
RowSmartTag = 0 
RowStyle = 8 
RowTab = 0 
RowTextXForm = 12 
RowText = 11 
RowUser = 0 
RowVertex = 1 
RowXForm1D = 4 
RowXFormOut = 1 
#End Enum 
 
#Public Enum VisRowTags 
TagArcTo = 140 
TagCnnctNamed = 185 
TagCnnctNamedABCD = 187 
TagCnnctPt = 153 
TagCnnctPtABCD = 186 
TagComponent = 137 
TagCtlPt = 162 
TagCtlPtTip = 170 
TagDefault = 0 
TagEllipse = 143 
TagEllipticalArcTo = 144 
TagInfiniteLine = 141 
TagLineTo = 139 
TagMoveTo = 138 
TagNURBSTo = 195 
TagPolylineTo = 193 
TagSplineBeg = 165 
TagSplineSpan = 166 
TagTab0 = 136 
TagTab10 = 151 
TagTab2 = 150 
TagTab60 = 181 
#End Enum 
 
#Public Enum VisRunTypes 
CharPropRow = 1 
FieldRun = 20 
ParaPropRow = 2 
ParaRun = 11 
TabPropRow = 3 
WordRun = 10 
#End Enum 
 
#Public Enum VisSavePreviewMode 
SavePreviewDraft1st = 1 
SavePreviewDraftAll = 4 
SavePreviewNone = 0 
#End Enum 
 
#Public Enum VisScrollbarStates 
ScrollBarBoth = 0x5 
ScrollBarHoriz = 0x1 
ScrollBarNeither = 0x0 
ScrollBarVert = 0x4 
#End Enum 
 
#Public Enum VisSectionIndices 
SectionAction = 240 
SectionAnnotation = 246 
SectionCharacter = 3 
SectionConnectionPts = 7 
SectionControls = 9 
SectionFirstComponent = 10 
SectionFirst = 0 
SectionHyperlink = 244 
SectionInval = 255 
SectionLastComponent = 239 
SectionLast = 252 
SectionLayer = 241 
SectionNone = 255 
SectionObject = 1 
SectionParagraph = 4 
SectionProp = 243 
SectionReviewer = 245 
SectionScratch = 6 
SectionSmartTag = 247 
SectionTab = 5 
SectionTextField = 8 
SectionUser = 242 
#End Enum 
 
#Public Enum VisSelectArgs 
Select = 2 
SubSelect = 3 
SelectAll = 4 
DeselectAll = 256 
#End Enum 
 
#Public Enum VisSelectionTypes 
SelTypeAll = 1 
SelTypeByDataGraphic = 6 
SelTypeByLayer = 3 
SelTypeByMaster = 5 
SelTypeByType = 4 
SelTypeEmpty = 0 
SelTypeSingle = 2 
#End Enum 
 
#Public Enum VisSelectItemStatus 
SelIsPrimaryItem = 0x1 
SelIsSubItem = 0x2 
SelIsSuperItem = 0x4 
#End Enum 
 
#Public Enum VisSelectMode 
SelModeOnlySub = 0x800 
SelModeOnlySuper = 0x200 
SelModeSkipSub = 0x400 
SelModeSkipSuper = 0x100 
#End Enum 
 
#Public Enum VisShapeIDs 
InvalShapeID = -1 
PageSheetID = 0 
#End Enum 
 
#Public Enum VisShapeTypes 
TypeBitmap = 32 
TypeDoc = 6 
TypeForeignObject = 4 
TypeGroup = 2 
TypeGuide = 5 
TypeInk = 64 
TypeInval = 0 
TypeIsControl = 1024 
TypeIsEmbedded = 512 
TypeIsLinked = 256 
TypeIsOLE2 = 32768 
TypeMetafile = 16 
TypePage = 1 
TypeShape = 3 
#End Enum 
 
#Public Enum VisSnapExtensions 
SnapExtAlignmentBoxExtension = 0x1 
SnapExtCenterAxes = 0x2 
SnapExtCurveExtension = 0x40 
SnapExtCurveTangent = 0x4 
SnapExtEllipseCenter = 0x800 
SnapExtEndpointHorizontal = 0x200 
SnapExtEndpointPerpendicular = 0x80 
SnapExtEndpointVertical = 0x400 
SnapExtEndpoint = 0x8 
SnapExtIsometricAngles = 0x1000 
SnapExtLinearExtension = 0x20 
SnapExtMidpointPerpendicular = 0x100 
SnapExtMidpoint = 0x10 
SnapExtNone = 0x0 
#End Enum 
 
#Public Enum VisSnapSettings 
SnapToAlignmentBox = 0x200 
SnapToConnectionPoints = 0x20 
SnapToDisabled = 0x8000 
SnapToExtensions = 0x400 
SnapToGeometry = 0x100 
SnapToGrid = 0x2 
SnapToGuides = 0x4 
SnapToHandles = 0x8 
SnapToIntersections = 0x10000 
SnapToNone = 0x0 
SnapToRulerSubdivisions = 0x1 
SnapToVertices = 0x10 
#End Enum 
 
#Public Enum VisSpatialRelationCodes 
SpatialContainedIn = 0x4 
SpatialContain = 0x2 
SpatialOverlap = 0x1 
SpatialTouching = 0x8 
#End Enum 
 
#Public Enum VisSpatialRelationFlags 
SpatialBackToFront = 0x8 
SpatialFrontToBack = 0x4 
SpatialIgnoreVisible = 0x20 
SpatialIncludeDataGraphics = 0x40 
SpatialIncludeGuides = 0x2 
SpatialIncludeHidden = 0x10 
#End Enum 
 
#Public Enum VisStatCodes 
StatAppHasShutdown = 1 
StatClosed = 8 
StatDeleted = 2 
StatNormal = 0 
StatSuspended = 16 
#End Enum 
 
#Public Enum VisTextDisplayQualityTypes 
TextDisplayClear = 2 
TextDisplayFaster = 0 
TextDisplayHigherQuality = 1 
#End Enum 
 
#Public Enum VisThemeColors 
ThemeColorsNone = 0 
ThemeColorsMonochrome = 1 
ThemeColorsOffice = 2 
ThemeColorsMedian = 3 
ThemeColorsConcourse = 4 
ThemeColorsSolstice = 5 
ThemeColorsTechnic = 6 
ThemeColorsPaper = 7 
ThemeColorsFoundry = 8 
ThemeColorsApex = 9 
ThemeColorsTrek = 10 
ThemeColorsModule = 11 
ThemeColorsOriel = 12 
ThemeColorsAspect = 13 
ThemeColorsEquity = 14 
ThemeColorsCivic = 15 
ThemeColorsOpulent = 16 
ThemeColorsVerve = 17 
ThemeColorsOrigin = 18 
ThemeColorsUrban = 19 
ThemeColorsFlow = 20 
ThemeColorsMetro = 21 
ThemeColorsOfficeLight = 22 
ThemeColorsOfficeDark = 23 
ThemeColorsMedianLight = 24 
ThemeColorsMedianDark = 25 
ThemeColorsConcourseLight = 26 
ThemeColorsConcourseDark = 27 
ThemeColorsPaperLight = 28 
ThemeColorsPaperDark = 29 
ThemeColorsFoundryLight = 30 
ThemeColorsFoundryDark = 31 
ThemeColorsEquityLight = 32 
ThemeColorsEquityDark = 33 
ThemeColorsVerveLight = 34 
ThemeColorsVerveDark = 35 
#End Enum 
 
#Public Enum VisThemeEffects 
ThemeEffectsNone = 0 
ThemeEffectsSubdued = 1 
ThemeEffectsSimpleShadow = 2 
ThemeEffectsButton = 3 
ThemeEffectsSquare = 4 
ThemeEffectsPillow = 5 
ThemeEffectsBevelIllusion = 6 
ThemeEffectsBevelHighlight = 7 
ThemeEffectsOutline = 8 
ThemeEffectsDecal = 9 
ThemeEffectsRaisedSurface = 10 
ThemeEffectsMesh = 11 
ThemeEffectsPinstripe = 12 
ThemeEffectsStripes = 13 
ThemeEffectsOblique = 14 
ThemeEffectsToy = 15 
#End Enum 
 
#Public Enum VisThemeTypes 
ThemeTypeColor = 1 
ThemeTypeEffect = 2 
#End Enum 
 
#Public Enum VisToParts 
ConnectionPoint = 100 
ConnectToError = -1 
GuideIntersect = 4 
GuideX = 1 
GuideY = 2 
ToAngle = 7 
ToNone = 0 
WholeShape = 3 
#End Enum 
 
#Public Enum VisTraceFlags 
TraceAddonInvokes = 0x4 
TraceAdvises = 0x2 
TraceCallsToVBA = 0x8 
TraceEvents = 0x1 
#End Enum 
 
#Public Enum VisTypeSelectionType 
TypeSelBitmap = 16 
TypeSelGroup = 1 
TypeSelGuide = 4 
TypeSelInk = 32 
TypeSelMetafile = 8 
TypeSelOLE = 64 
TypeSelShape = 2 
#End Enum 
 
#Public Enum VisUIBarPosition 
BarBottom = 3 
BarFloating = 4 
BarLeft = 0 
BarMenu = 6 
BarPopup = 5 
BarRight = 2 
BarTop = 1 
#End Enum 
 
#Public Enum VisUIBarProtection 
BarNoChangeDock = 16 
BarNoCustomize = 1 
BarNoHorizontalDock = 64 
BarNoMove = 4 
BarNoProtection = 0 
BarNoResize = 2 
BarNoVerticalDock = 32 
#End Enum 
 
#Public Enum VisUIBarRow 
BarRowFirst = 0 
BarRowLast = -1 
#End Enum 
 
#Public Enum VisUIButtonState 
ButtonDown = -1 
ButtonUp = 0 
#End Enum 
 
#Public Enum VisUIButtonStyle 
ButtonAutomatic = 0 
ButtonCaption = 2 
ButtonIconandCaption = 3 
ButtonIcon = 1 
#End Enum 
 
#Public Enum VisUICmds 
CmdABarAutoHeight = 1684 
CmdABarAutohide = 1652 
CmdABarHide = 1650 
CmdABarToggleFloat = 1651 
CmdAcquireImages = 1868 
CmdAddConnectPt = 1263 
CmdAddControlPt = 1266 
CmdAddDataRecordset = 1998 
CmdAddTextShape = 1181 
CmdAlignBox = 1768 
CmdAlignObjectBottom = 1201 
CmdAlignObjectCenter = 1197 
CmdAlignObjectLeft = 1196 
CmdAlignObjectMiddle = 1200 
CmdAlignObjectRight = 1198 
CmdAlignObjectTop = 1199 
CmdAllowThemes = 2056 
CmdApplyDataGraphic = 2017 
CmdApplyDataGraphicAfterLink = 2092 
CmdApplyThemeToDoc = 2048 
CmdApplyThemeToPage = 2047 
CmdAppMaximize = 1864 
CmdAppMinimize = 1865 
CmdAppRestore = 1904 
CmdAutoConnectToggle = 2091 
CmdAutoGenerateDataGraphics = 2105 
CmdBreakOLELink = 1900 
CmdBrowseSampleDrawings = 1645 
CmdBullets = 1633 
CmdCancelInPlaceEditing = 1602 
CmdCenterDrawing = 1202 
CmdCloseWindow = 1361 
CmdConnectorEffectCurved = 1945 
CmdConnectorEffectRightAngle = 1943 
CmdConnectorEffectStraight = 1944 
CmdConnPoints = 1774 
CmdCreateEditMaster = 1899 
CmdCreateNewDrawing = 1812 
CmdCreateShortcut = 1791 
CmdCropObject = 1192 
CmdCropTool = 1449 
CmdCustomPropertySets = 1675 
CmdCustProp = 1658 
CmdCustPropDefine = 1695 
CmdDataAutoConnect = 2098 
CmdDataAutoLink = 2046 
CmdDataAutoLinkWiz = 2045 
CmdDataColumnSettingsDlg = 2043 
CmdDataExplorerWindow = 2044 
CmdDataRecordsetProperties = 2072 
CmdDataRecordsetSetCommand = 2037 
CmdDataRecordsetSetPrimaryKey = 2038 
CmdDataRefresh = 2021 
CmdDataRefreshAddConflict = 2094 
CmdDataRefreshConfigDlg = 2022 
CmdDataRefreshDeleteConflict = 2095 
CmdDataRefreshDlg = 2019 
CmdDataRefreshResolveConflict = 2103 
CmdDataSelectorDlg = 2011 
CmdDataUnlinkRow = 2058 
CmdDataUnlinkShape = 2057 
CmdDecreaseIndent = 1093 
CmdDecreaseParaSpacing = 1095 
CmdDelConnectPt = 1265 
CmdDelControlPt = 1268 
CmdDeleteBackWord = 1905 
CmdDeleteComment = 1920 
CmdDeleteDataGraphic = 2067 
CmdDeleteDataRecordset = 1999 
CmdDeleteForwardWord = 2114 
CmdDeleteTheme = 2052 
CmdDeselectAll = 1213 
CmdDesignMode = 1388 
CmdDetectAndRepair = 1890 
CmdDistributeBottom = 1238 
CmdDistributeCenter = 1233 
CmdDistributeHSpace = 1231 
CmdDistributeLeft = 1232 
CmdDistributeMiddle = 1237 
CmdDistributeRight = 1234 
CmdDistributeTop = 1236 
CmdDistributeVSpace = 1235 
CmdDlgCustomFit = 1536 
CmdDragDuplicate = 1184 
CmdDrawFillStyle = 1123 
CmdDrawGlue = 1125 
CmdDrawAddGuide = 1180 
CmdDrawingExplorer = 1721 
CmdDrawingTools = 1946 
CmdDrawLineStyle = 1122 
CmdDrawOval = 1183 
CmdDrawSnap = 1124 
CmdDrawRect = 1182 
CmdDrawRegion = 1742 
CmdDrawTextStyle = 1121 
CmdDrawZoom = 1126 
CmdDRConnectionTool = 1226 
CmdDRConnectorTool = 1225 
CmdDRLineTool = 1221 
CmdDropManyOnPage = 1869 
CmdDropManyLinked = 2108 
CmdDropOnPage = 1246 
CmdDropOnStencil = 1244 
CmdDropOnText = 1243 
CmdDROvalTool = 1224 
CmdDRPencilTool = 1220 
CmdDRPointerTool = 1219 
CmdDRQtrArcTool = 1222 
CmdDRRectTool = 1223 
CmdDRRotateTool = 1228 
CmdDRSplineTool = 1311 
CmdDRTextTool = 1227 
CmdDuplicateDataGraphic = 2106 
CmdDuplicateTheme = 2050 
CmdEditRedoMultiple = 1683 
CmdEditTheme = 2049 
CmdEditUndoMultiple = 1682 
CmdDynamicGrid = 1765 
CmdDynConnReroute = 1829 
CmdEditConvertObject = 1439 
CmdEditFind = 1043 
CmdEditInsertField = 1032 
CmdEditInsertObject = 1031 
CmdEditLinks = 1030 
CmdEditOpenObject = 1029 
CmdEditPasteLink = 1028 
CmdEditPasteSpecial = 1027 
CmdEditRedo = 1018 
CmdEditRepeat = 1019 
CmdEditReplace = 1179 
CmdEditSelectSpecial = 1026 
CmdEditUndo = 1017 
CmdEmailRouting = 1588 
CmdExportDatabaseAddon = 1891 
CmdFileCheckin = 1787 
CmdFileCheckout = 1788 
CmdFileChooseTemplates = 1583 
CmdFileClose = 1003 
CmdFileExit = 1016 
CmdFileImport = 1007 
CmdFileLastFile1 = 1012 
CmdFileLastFile2 = 1013 
CmdFileLastFile3 = 1014 
CmdFileLastFile4 = 1015 
CmdFileLastFile5 = 1561 
CmdFileLastFile6 = 1569 
CmdFileLastFile7 = 1570 
CmdFileLastFile8 = 1571 
CmdFileLastFile9 = 1572 
CmdFileNew = 1001 
CmdFileNewBlankDrawing = 1579 
CmdFileNewBlankDrawingMetric = 1671 
CmdFileNewBlankDrawingUS = 1672 
CmdFileNewBlankStencil = 1582 
CmdFileNewBlankStencilMetric = 1673 
CmdFileNewBlankStencilUS = 1674 
CmdFileNewStencilDlg = 1580 
CmdFileOpen = 1002 
CmdFileOpenStencil = 1442 
CmdFilePrint = 1010 
CmdFileSave = 1004 
CmdFileSaveAs = 1005 
CmdFileSaveAsWebPage = 1785 
CmdFileSaveWorkspace = 1006 
CmdFileSummaryInfoDlg = 1009 
CmdFileUndoCheckout = 2109 
CmdFirstTile = 1515 
CmdFitCurve = 1538 
CmdFormatAllTextProps = 1642 
CmdFormatBehavior = 1071 
CmdFormatBlock = 1070 
CmdFormatCorners = 1334 
CmdFormatCustPropDef = 1687 
CmdFormatCustPropEdit = 1312 
CmdFormatDefineStyles = 1064 
CmdFormatDoubleClick = 1118 
CmdFormatFill = 1066 
CmdFormatInkDlg = 1955 
CmdFormatLine = 1065 
CmdFormatPainter = 1271 
CmdFormatParagraph = 1068 
CmdFormatProtection = 1072 
CmdFormatShadow = 1333 
CmdFormatSpecial = 1073 
CmdFormatStyle = 1063 
CmdFormatTabs = 1069 
CmdFormatText = 1067 
CmdFullScreenMode = 1492 
CmdGoToPageToolbar = 1635 
CmdGrid = 1767 
CmdGuides = 1771 
CmdHeaderFooter = 1720 
CmdHelpAboutVisio = 1100 
CmdHelpContents = 1092 
CmdHelpMode = 1386 
CmdHelpSearch = 1809 
CmdHelpShapeBasics = 1822 
CmdHelpTemplates = 1586 
CmdHideAllToolbars = 1726 
CmdHideDocumentStencil = 1689 
CmdHyperlinkHier = 1611 
CmdHyperlinkList = 1719 
CmdIconBucketTool = 1543 
CmdIconLassoTool = 1544 
CmdIconLeftColor = 1143 
CmdIconPencilTool = 1145 
CmdIconRightTool = 1144 
CmdIconSelectNet = 1545 
CmdImageProperties = 1887 
CmdImagePropertiesDlg = 1883 
CmdIncreaseIndent = 1094 
CmdIncreaseParaSpacing = 1096 
CmdINETAddToFavorites = 1506 
CmdINETCopyHyperlink = 1610 
CmdINETDeleteHlink = 1609 
CmdINETDiagrammingResources = 1606 
CmdINETEditHyperlink = 1619 
CmdINETGoBack = 1599 
CmdINETGoForward = 1598 
CmdINETKnowledgeBase = 1605 
CmdINETOpenHLink = 1607 
CmdINETOpenHLinkNewWnd = 1608 
CmdINETPasteAsHyperlink = 1620 
CmdINETUserSearchPage = 1595 
CmdINETVisioHomePage = 1596 
CmdINETVisioOnTheWeb = 1831 
CmdINETVisioSolutionsLibrary = 1604 
CmdInkCustomizePen = 1664 
CmdInkEraser = 1970 
CmdInkReviewPen = 1971 
CmdInkStockPen0 = 1973 
CmdInkStockPen1 = 1974 
CmdInkStockPen2 = 1975 
CmdInkStockPen3 = 1976 
CmdInkStockPen4 = 1977 
CmdInkTool = 1661 
CmdInsertAutoCADAddOn = 1521 
CmdInsertClipArt = 1497 
CmdInsertComment = 1501 
CmdInsertControlDlg = 1522 
CmdInsertDataMap = 1282 
CmdInsertHyperLink = 1585 
CmdInsertMicrosoftGraph = 1499 
CmdInsertTextBox = 2006 
CmdInsertVertTextBox = 2007 
CmdInsertWordArt = 1498 
CmdIntersect = 1453 
CmdJoin = 1533 
CmdLastTile = 1516 
CmdLayerDlg = 1446 
CmdLayerSetupDlg = 1448 
CmdLayoutDynamic = 1493 
CmdLinkRowToShape = 1997 
CmdMasterExplorer = 1916 
CmdMasterSetup = 1343 
CmdMDIMaximize = 1901 
CmdMDIMinimize = 1902 
CmdMDIRestore = 1903 
CmdModConnectPt = 1264 
CmdModControlPt = 1267 
CmdMovConnectPt = 1269 
CmdMove1D = 1186 
CmdMove2D = 1187 
CmdMoveComment = 1502 
CmdMoveObject = 1185 
CmdMsoAutoCorrect = 1872 
CmdMsoAutoCorrectDlg = 1866 
CmdMsoAutoFormat = 1873 
CmdMsoCustomItem = 1896 
CmdMSOInsertEquation = 1646 
CmdMSOInsertSymbol = 1504 
CmdMSOInsertSymbolDlg = 1505 
CmdMsoMediaGallery = 1885 
CmdNewDefDocBlankDrawing = 1906 
CmdNewFromExisting = 1897 
CmdNewThemeColors = 2065 
CmdNewThemeEffects = 2064 
CmdNextMarkup = 1914 
CmdNextTile = 1514 
CmdNextWindow = 1886 
CmdObjectAddToGroup = 1053 
CmdObjectAlignObjects = 1049 
CmdObjectBringForward = 1045 
CmdObjectBringToFront = 1046 
CmdObjectCombine = 1061 
CmdObjectConnectObjects = 1050 
CmdObjectConvertToGroup = 1055 
CmdObjectDistributeDlg = 1230 
CmdObjectFlipHorizontal = 1058 
CmdObjectFlipVertical = 1057 
CmdObjectFragment = 1062 
CmdObjectGroup = 1051 
CmdObjectHelp = 1428 
CmdObjectInfoDlg = 1425 
CmdObjectRemoveFromGroup = 1054 
CmdObjectReverse = 1059 
CmdObjectRotate90 = 1056 
CmdObjectSendBackward = 1047 
CmdObjectSendToBack = 1048 
CmdObjectSwapEnds = 1870 
CmdObjectUngroup = 1052 
CmdObjectUnion = 1060 
CmdOffsetDlg = 1387 
CmdOfficeDiagnostics = 1890 
CmdOpenActiveObject = 1601 
CmdOpenCommentForEdit = 1503 
CmdOpenInVisio = 1491 
CmdOptionsColorPaletteDlg = 1082 
CmdOptionsDeletePages = 1079 
CmdOptionsEditBackground = 1075 
CmdOptionsEditDrawing = 1074 
CmdOptionsGoToDrawing = 1077 
CmdOptionsNewPage = 1078 
CmdOptionsPageSetup = 1076 
CmdOptionsPreferences = 1081 
CmdOptionsProtectDocument = 1083 
CmdOptionsReorderPages = 1080 
CmdOptionsSnapGlueSetup = 1084 
CmdPageMeasureUnitsDlg = 1274 
CmdPagesList = 1654 
CmdPanObject = 1193 
CmdPanZoom = 1653 
CmdPasteShortcut = 1790 
CmdPauseRecordingMacro = 1778 
CmdPreviousMarkup = 1915 
CmdPreviousTile = 1513 
CmdPrintPage = 1443 
CmdPrintPreview = 1490 
CmdProgRefHelp = 1584 
CmdRecalcObjectWH = 1146 
CmdRecordNewMacro = 1775 
CmdRelayoutShapes = 2068 
CmdRemoveDataGraphicFromSel = 2107 
CmdRemoveThemeFromSel = 2119 
CmdRemoveVBAFromActiveDoc = 1590 
CmdRHI = 2009 
CmdRHIDlg = 2010 
CmdReOrderPage = 1795 
CmdResearchLookUp = 1967 
CmdResearchTranslate = 1968 
CmdResumeRecordingMacro = 1779 
CmdReviewerVisibilityAll = 1836 
CmdReviewerVisibilityNone = 1919 
CmdRightDragCancel = 1881 
CmdRightDragCopy = 1879 
CmdRightDragLink = 1880 
CmdRightDragMove = 1878 
CmdRotate90Clockwise = 1494 
CmdRotateObject = 1190 
CmdRulerGridDlg = 1318 
CmdRulSub = 1766 
CmdRunAddOnDlg = 1484 
CmdRunAddonMenu = 1090 
CmdSaveAsFixedFormatDlg = 2117 
CmdSelectionModeExtend = 1909 
CmdSelectionModeLasso = 1908 
CmdSelectionModeRect = 1907 
CmdSendAsMail = 1292 
CmdSendToExchange = 1589 
CmdSetAddMarkup = 1744 
CmdSetCharColor = 1404 
CmdSetCharSizeDown = 1406 
CmdSetCharSizeUp = 1405 
CmdSetDynConnAppearanceCurved = 1895 
CmdSetDynConnAppearanceDefault = 1893 
CmdSetDynConnAppearanceStraight = 1894 
CmdSetDynConnLineJumpStyle_2pt = 1713 
CmdSetDynConnLineJumpStyle_3pt = 1714 
CmdSetDynConnLineJumpStyle_4pt = 1715 
CmdSetDynConnLineJumpStyle_5pt = 1716 
CmdSetDynConnLineJumpStyle_6pt = 1717 
CmdSetDynConnLineJumpStyle_Arc = 1709 
CmdSetDynConnLineJumpStyle_Gap = 1710 
CmdSetDynConnLineJumpStyle_Page = 1708 
CmdSetDynConnLineJumpStyle_Square = 1711 
CmdSetDynConnLineJumpStyle_Triangle = 1712 
CmdSetDynConnRerouteAsNeeded = 1697 
CmdSetDynConnRerouteFreely = 1696 
CmdSetDynConnRerouteNever = 1698 
CmdSetDynConnRerouteOnCrossover = 1837 
CmdSetDynConnRoutingStyle = 1700 
CmdSetFillColor = 1385 
CmdSetFillPattern = 1399 
CmdSetFillShadow = 1379 
CmdSetHeaderFooter = 1858 
CmdSetIndexInStencil = 1871 
CmdSetLanguageDlg = 1888 
CmdSetLineColor = 1359 
CmdSetLineCornerStyle = 1358 
CmdSetLineEnds = 1357 
CmdSetLinePattern = 1356 
CmdSetLineWeight = 1355 
CmdSetPageLineJumpCode_D = 1703 
CmdSetPageLineJumpCode_Horz = 1705 
CmdSetPageLineJumpCode_Last = 1707 
CmdSetPageLineJumpCode_None = 1704 
CmdSetPageLineJumpCode_Vert = 1706 
CmdSetPagePlow = 1699 
CmdShapeActions = 1309 
CmdShapeComment = 1686 
CmdShapeCommentDelete = 1688 
CmdShapeCommentDlg = 1685 
CmdShapeExplorer = 1389 
CmdShapeGalleryAddOn = 1867 
CmdShapeGeo = 1769 
CmdShapeHand = 1772 
CmdShapeIntersect = 1830 
CmdShapeLayerToolbar = 1634 
CmdShapeStudioAddOn = 1985 
CmdShapesWindow = 1669 
CmdShapeTransparency = 1875 
CmdShapeTransparencyDlg = 1874 
CmdShapeVert = 1773 
CmdSize1D = 1188 
CmdSize2D = 1189 
CmdSizeObjects = 1925 
CmdSizePos = 1670 
CmdSizeTextBlock = 1194 
CmdSpellingChange = 1889 
CmdSpellingOptionsDlg = 2042 
CmdSSWindowAddSection = 1384 
CmdSSWindowChangeRowType = 1383 
CmdSSWindowCollapse = 1250 
CmdSSWindowDeselect = 1253 
CmdSSWindowExpand = 1251 
CmdSSWindowPasteFunction = 1382 
CmdSSWindowPasteName = 1381 
CmdSSWindowSelect = 1252 
CmdSSWindowShowSection = 1380 
CmdSSWindowShowTraceWindow = 1781 
CmdStampTool = 1424 
CmdStartRecordingMacro = 1776 
CmdStenActivate = 1458 
CmdStenAutoArrange = 1483 
CmdStenCleanup = 1106 
CmdStenClose = 1452 
CmdStenDrawingExplorer = 1796 
CmdStenEditDrawing = 1102 
CmdStenEditIcon = 1101 
CmdStenEditOff = 1681 
CmdStenEditOn = 1680 
CmdStenEditToggle = 1679 
CmdStenIconAndDetail = 1892 
CmdStenIconAndName = 1480 
CmdStenIconOnly = 1481 
CmdStenImageMaster = 1105 
CmdStenNameMaster = 1103 
CmdStenNameOnly = 1482 
CmdStenNamesUnderIcons = 2005 
CmdStenNewMaster = 1104 
CmdStenProperties = 1678 
CmdStenSave = 1676 
CmdStenSaveAs = 1677 
CmdStopRecordingMacro = 1777 
CmdSubtract = 1454 
CmdSWAccept = 1140 
CmdSWAddSectionDlg = 1116 
CmdSWCancel = 1139 
CmdSWChangeRowTypeDlg = 1114 
CmdSWDeleteRow = 1115 
CmdSWDeleteSection = 1117 
CmdSWExpandRow = 1718 
CmdSWFormula = 1141 
CmdSWInsertRow = 1112 
CmdSWInsertRowAfter = 1113 
CmdSWPasteFunctionDlg = 1111 
CmdSWPasteNameDlg = 1110 
CmdSWShapeActionDlg = 1444 
CmdSWShowFormulas = 1108 
CmdSWShowSectionsDlg = 1109 
CmdSWShowToggle = 1142 
CmdSWShowValues = 1107 
CmdTaskPane = 1896 
CmdTaskPaneDataGraphic = 2024 
CmdTaskPaneDocumentManagement = 1972 
CmdTaskPaneResearch = 1969 
CmdTaskPaneReviewer = 1939 
CmdTaskPaneThemeColors = 2054 
CmdTaskPaneThemeEffects = 2055 
CmdTaskTogglePreviewSize = 2053 
CmdTextAllCaps = 1862 
CmdTextBlockTool = 1451 
CmdTextBold = 1131 
CmdTextDoubleStrikeThrough = 1951 
CmdTextDoubleULine = 1863 
CmdTextEditRuler = 1810 
CmdTextEditState = 1214 
CmdTextFont = 1129 
CmdTextHAlignCenter = 1408 
CmdTextHAlignDistribute = 1952 
CmdTextHAlignJustify = 1412 
CmdTextHAlignLeft = 1407 
CmdTextHAlignRight = 1409 
CmdTextItalic = 1132 
CmdTextRotate90 = 1098 
CmdTextSize = 1130 
CmdTextSmallCaps = 1133 
CmdTextStrikeThrough = 1741 
CmdTextStyle = 1128 
CmdTextSubscript = 1135 
CmdTextSuperScript = 1134 
CmdTextULine = 1136 
CmdTextVAlignBottom = 1422 
CmdTextVAlignMiddle = 1414 
CmdTextVAlignTop = 1413 
CmdToggleDocumentStencil = 1690 
CmdToolbarsDlg = 1500 
CmdToolsArrayShapesAddOn = 1354 
CmdToolsInventory = 1335 
CmdToolsLayoutShapesDlg = 1574 
CmdToolsMacroDlg = 1577 
CmdToolSnapLines = 1807 
CmdToolsRunVBE = 1576 
CmdToolsSpelling = 1270 
CmdTrim = 1534 
CmdTrustCenterDlg = 2104 
CmdTurnToNextPage = 1148 
CmdTurnToPrevPage = 1147 
CmdUFEditClear = 1023 
CmdUFEditCopy = 1021 
CmdUFEditCut = 1020 
CmdUFEditDuplicate = 1024 
CmdUFEditPaste = 1022 
CmdUFEditSelectAll = 1025 
CmdUpdateColumnsInLinkedShapes = 2061 
CmdView100 = 1035 
CmdView150 = 1036 
CmdView200 = 1037 
CmdView400 = 1280 
CmdView50 = 1279 
CmdView75 = 1034 
CmdViewConnections = 1042 
CmdViewCustom = 1038 
CmdViewDirectionToggle = 2012 
CmdViewFitInWindow = 1033 
CmdViewGrid = 1040 
CmdViewGuides = 1041 
CmdViewLeftToRight = 2013 
CmdViewPageBreaks = 1509 
CmdViewRightToLeft = 2014 
CmdViewRulers = 1039 
CmdViewStatusBar = 1044 
CmdWindowCascadeAll = 1086 
CmdWindowNewWindow = 1085 
CmdWindowShowDrawPage = 1091 
CmdWindowShowMasterObjects = 1089 
CmdWindowShowShapeSheet = 1088 
CmdWindowTileAll = 1087 
CmdZoomArea = 1218 
CmdZoomIn = 1216 
CmdZoomInIgnoreSel = 1917 
CmdZoomLast = 1495 
CmdZoomOut = 1217 
CmdZoomOutIgnoreSel = 1918 
CmdZoomPageWidth = 1496 
CmdZoomPt = 1215 
CmdZoomSingleTile = 1512 
#End Enum 
 
#Public Enum VisUICtrlTypes 
CtrlTypeBUTTON_OWNERDRAW = 33 
CtrlTypeBUTTON = 2 
CtrlTypeCOMBOBOX = 128 
CtrlTypeDROPDOWN = 272 
CtrlTypeEDITBOX = 64 
CtrlTypeLABEL = 2048 
CtrlTypeSPLITBUTTON_MRU_COLOR = 16 
CtrlTypeSPLITBUTTON_MRU_COMMAND = 18 
CtrlTypeSPLITBUTTON = 17 
#End Enum 
 
#Public Enum VisUIIconIDs 
IconIXACCEPT = 85 
IconIXADDIN = 149 
IconIXALIGNBOTTOM = 69 
IconIXALIGNBOX = 224 
IconIXALIGNCENTER = 65 
IconIXALIGNLEFT = 64 
IconIXALIGNMIDDLE = 68 
IconIXALIGNRIGHT = 66 
IconIXALIGNTOP = 67 
IconIXALIGN = 63 
IconIXARRANGE = 83 
IconIXBOLD = 50 
IconIXBRING_FORWARD = 245 
IconIXBRINGFRONT = 90 
IconIXBULLETS = 113 
IconIXCANCEL = 84 
IconIXCANTFIND = 129 
IconIXCASCADE = 94 
IconIXCHART = 134 
IconIXCHECKMARK = 128 
IconIXCLEAR = 9 
IconIXCLIPART = 130 
IconIXCLOSE = 143 
IconIXCONNECTIONPOINTS = 36 
IconIXCONNECTIONPTTOOL = 30 
IconIXCONNECTORTOOL = 96 
IconIXCONNECTSHAPES = 75 
IconIXCONNPOINTS = 229 
IconIXCOPY = 7 
IconIXCORNERSTYLE = 40 
IconIXCROP = 29 
IconIXCUSTOM_BALLOON = 162 
IconIXCUSTOM_BANK = 153 
IconIXCUSTOM_BELL = 159 
IconIXCUSTOM_BOX = 173 
IconIXCUSTOM_CALC = 164 
IconIXCUSTOM_CAMCORD = 163 
IconIXCUSTOM_CARDS = 169 
IconIXCUSTOM_CLUB = 168 
IconIXCUSTOM_DIAMOND = 166 
IconIXCUSTOM_DOWN = 178 
IconIXCUSTOM_EIGHTBALL = 191 
IconIXCUSTOM_EYE = 190 
IconIXCUSTOM_FEET = 174 
IconIXCUSTOM_FISH = 182 
IconIXCUSTOM_FROWN = 152 
IconIXCUSTOM_GEARS = 184 
IconIXCUSTOM_HEART = 165 
IconIXCUSTOM_HOURGLASS = 186 
IconIXCUSTOM_KEYBOARD = 180 
IconIXCUSTOM_KEY = 183 
IconIXCUSTOM_LEFT = 175 
IconIXCUSTOM_LOAD = 155 
IconIXCUSTOM_MAN = 187 
IconIXCUSTOM_MIC = 157 
IconIXCUSTOM_MUG = 170 
IconIXCUSTOM_NOTE = 160 
IconIXCUSTOM_PAGES = 181 
IconIXCUSTOM_PASTE = 154 
IconIXCUSTOM_PENCIL = 172 
IconIXCUSTOM_PHONE = 161 
IconIXCUSTOM_QUESTION = 192 
IconIXCUSTOM_RIGHT = 176 
IconIXCUSTOM_RUN = 189 
IconIXCUSTOM_SAVE = 156 
IconIXCUSTOM_SCALES = 185 
IconIXCUSTOM_SMILE = 151 
IconIXCUSTOM_SPADE = 167 
IconIXCUSTOM_SPEAKER = 158 
IconIXCUSTOM_TACK = 179 
IconIXCUSTOM_TRASH = 171 
IconIXCUSTOM_UP = 177 
IconIXCUSTOM_WOMAN = 188 
IconIXCUSTOMPROP_WINDOW = 215 
IconIXCUSTPROP = 111 
IconIXCUT = 6 
IconIXDCREROUTE_ASNEEDED = 214 
IconIXDCREROUTE_FREELY = 213 
IconIXDCREROUTE_NEVER = 235 
IconIXDCREROUTE = 236 
IconIXDECRINDENT = 114 
IconIXDECRPARA = 116 
IconIXDELETECOMMENT = 195 
IconIXDELETE = 196 
IconIXDESIGNMODE = 119 
IconIXDHORZ_CENTER = 72 
IconIXDHORZ_EQSPACE = 71 
IconIXDISTRIBUTE = 70 
IconIXDOUBLE_UNDERLINE = 253 
IconIXDRAWINGEXPLORER = 219 
IconIXDVERT_EQSPACE = 73 
IconIXDVERT_MIDDLE = 74 
IconIXDYNGRID = 221 
IconIXEDITCOMMENT = 194 
IconIXEDITSTEN = 197 
IconIXEXCHANGEFOLDER = 137 
IconIXFILLCOLOR = 43 
IconIXFILLPATTERN = 47 
IconIXFIND = 138 
IconIXFIRSTPAGE = 76 
IconIXFLIPHORIZONTAL = 18 
IconIXFLIPVERTICAL = 19 
IconIXFOLDER = 144 
IconIXFORMATPAINTER = 101 
IconIXFULLSCREEN = 124 
IconIXGLUE = 32 
IconIXGOBACK = 107 
IconIXGOFORWARD = 108 
IconIXGRID = 34 
IconIXGROUP = 92 
IconIXGUIDES = 226 
IconIXGUIDE = 35 
IconIXHELPASSISTANT = 133 
IconIXHELPBOOK = 125 
IconIXHELPMODE = 102 
IconIXICONBUCKET = 87 
IconIXICONLASSO = 88 
IconIXICONNAME = 80 
IconIXICONONLY = 81 
IconIXICONPENCIL = 86 
IconIXICONSELNET = 89 
IconIXIMAGE = 131 
IconIXINCRINDENT = 115 
IconIXINCRPARA = 117 
IconIXINSERT_EQUATION = 250 
IconIXINSERT_OBJECT = 248 
IconIXINSERTCOMMENT = 193 
IconIXINSERTCONTROL = 118 
IconIXINSERTHYPERLINK = 105 
IconIXITALIC = 51 
IconIXLARGE_PADLOCK = 249 
IconIXLASTPAGE = 77 
IconIXLAYERPROPERTIES = 103 
IconIXLAYOUTSHAPES = 104 
IconIXLINECOLOR = 44 
IconIXLINEEND = 41 
IconIXLINEJUMPSTYLE_2PT = 208 
IconIXLINEJUMPSTYLE_3PT = 209 
IconIXLINEJUMPSTYLE_4PT = 210 
IconIXLINEJUMPSTYLE_5PT = 211 
IconIXLINEJUMPSTYLE_6PT = 212 
IconIXLINEJUMPSTYLE_ARC = 204 
IconIXLINEJUMPSTYLE_GAP = 205 
IconIXLINEJUMPSTYLE_PAGE = 218 
IconIXLINEJUMPSTYLE_SQUARE = 206 
IconIXLINEJUMPSTYLE_TRIANGLE = 207 
IconIXLINEPATTERN = 46 
IconIXLINETOOL = 22 
IconIXLINEWEIGHT = 45 
IconIXMACROS = 121 
IconIXMAILRECPT = 135 
IconIXMAXIMIZE = 142 
IconIXMINIMIZE = 141 
IconIXNAMEONLY = 82 
IconIXNEWSTEN = 198 
IconIXNEWWINDOW = 39 
IconIXNEW = 0 
IconIXNEXTPAGE = 14 
IconIXOPENSTENCIL = 2 
IconIXOPEN = 1 
IconIXOVALTOOL = 25 
IconIXPAGEBREAKS = 78 
IconIXPAGELINEJUMPCODE_DISP = 217 
IconIXPAGELINEJUMPCODE_HORZ = 201 
IconIXPAGELINEJUMPCODE_LASTROUTED = 203 
IconIXPAGELINEJUMPCODE_NONE = 200 
IconIXPAGELINEJUMPCODE_RDISP = 231 
IconIXPAGELINEJUMPCODE_VERT = 202 
IconIXPAGEPLOW = 216 
IconIXPANZOOM = 139 
IconIXPASTE = 8 
IconIXPENCILTOOL = 21 
IconIXPOINTERTOOL = 20 
IconIXPOINTSIZEDOWN = 48 
IconIXPOINTSIZEUP = 49 
IconIXPREVIOUSPAGE = 13 
IconIXPRINTPREVIEW = 5 
IconIXPRINT = 4 
IconIXQTRARCTOOL = 23 
IconIXRECTANGLETOOL = 24 
IconIXREDO = 11 
IconIXREPEAT = 12 
IconIXREPLACE = 252 
IconIXRESTORE = 140 
IconIXROTATECLOCKWISE = 37 
IconIXROTATECOUNTERCLOCKWISE = 38 
IconIXROTATETEXT = 112 
IconIXROTATETOOL = 28 
IconIXROUTINGRECPT = 136 
IconIXRULER = 33 
IconIXRULSUB = 222 
IconIXSAVE = 3 
IconIXSEARCHTHEWEB = 106 
IconIXSEND_BACKWARD = 246 
IconIXSENDBACK = 91 
IconIXSHADOWSTYLE = 42 
IconIXSHAPE_INTERSECT = 220 
IconIXSHAPEEXPLORER = 126 
IconIXSHAPEEXPL = 110 
IconIXSHAPEEXT = 230 
IconIXSHAPEGEO = 225 
IconIXSHAPEHAND = 227 
IconIXSHAPESHEET = 120 
IconIXSHAPEVERT = 228 
IconIXSHOWDOCSTEN = 199 
IconIXSINGLETILE = 99 
IconIXSIZEPOS = 150 
IconIXSMALL_PADLOCK = 247 
IconIXSMALLCAPS = 234 
IconIXSNAP_LINES = 232 
IconIXSNAPTOGRID = 223 
IconIXSNAP = 31 
IconIXSPELLING = 100 
IconIXSPLINETOOL = 79 
IconIXSTAMPTOOL = 26 
IconIXSTRIKETHROUGH = 233 
IconIXSTYLE = 251 
IconIXSUBSCRIPT = 54 
IconIXSUPERSCRIPT = 53 
IconIXTEXTALIGNBOTTOM = 62 
IconIXTEXTALIGNCENTER = 57 
IconIXTEXTALIGNJUSTIFY = 59 
IconIXTEXTALIGNLEFT = 56 
IconIXTEXTALIGNMIDDLE = 61 
IconIXTEXTALIGNRIGHT = 58 
IconIXTEXTALIGNTOP = 60 
IconIXTEXTBLOCKTOOL = 97 
IconIXTEXTCOLOR = 55 
IconIXTEXTOOL = 27 
IconIXTILE = 95 
IconIXUNDERLINE = 52 
IconIXUNDO = 10 
IconIXUNGROUP = 93 
IconIXVBAMACRO = 148 
IconIXVBEDITOR = 122 
IconIXVERTICALTEXT = 123 
IconIXVSD = 145 
IconIXVSS = 146 
IconIXVST = 147 
IconIXWEBPAGE = 127 
IconIXWEBTOOLBAR = 109 
IconIXWHOLEPAGE = 98 
IconIXWORDART = 132 
IconIXZOOM100 = 17 
IconIXZOOMIN = 16 
IconIXZOOMOUT = 15 
#End Enum 
 
#Public Enum VisUIMenuAnimation 
MenuAnimationNone = 0 
MenuAnimationRandom = 1 
MenuAnimationSlide = 3 
MenuAnimationUnfold = 2 
#End Enum 
 
#Public Enum VisUIObjSets 
UIObjSetActiveXDoc = 18 
UIObjSetCntx_AddComments = 1000 
UIObjSetCntx_AnchorBar_Base = 61 
UIObjSetCntx_AnchorBar_CustProp = 62 
UIObjSetCntx_AnchorBar_Shapes = 69 
UIObjSetCntx_AnchorBar_SizePos = 63 
UIObjSetCntx_BuiltInMenus = 1010 
UIObjSetCntx_CommentMarker = 68 
UIObjSetCntx_ConnectPtType = 44 
UIObjSetCntx_DEDocument = 49 
UIObjSetCntx_DELayers = 54 
UIObjSetCntx_DELayer = 55 
UIObjSetCntx_DEMasters = 58 
UIObjSetCntx_DEMaster = 59 
UIObjSetCntx_DEPages = 50 
UIObjSetCntx_DEPage = 51 
UIObjSetCntx_DEPatterns = 60 
UIObjSetCntx_DEShapes = 52 
UIObjSetCntx_DEShape = 53 
UIObjSetCntx_DEStyles = 56 
UIObjSetCntx_DEStyle = 57 
UIObjSetCntx_DrawObjSel = 9 
UIObjSetCntx_DrawOleObjSel = 10 
UIObjSetCntx_Fullscreen = 17 
UIObjSetCntx_Master = 14 
UIObjSetCntx_MEDocument = 66 
UIObjSetCntx_MEMasters = 67 
UIObjSetCntx_PageTabs = 47 
UIObjSetCntx_ShapeSheet = 15 
UIObjSetCntx_Stencil = 21 
UIObjSetCntx_TextEdit = 13 
UIObjSetDrawing = 2 
UIObjSetHostingInPlace = 22 
UIObjSetIcon = 5 
UIObjSetInPlace = 6 
UIObjSetPal_AlignShapes = 30 
UIObjSetPal_ConnectorTool = 40 
UIObjSetPal_CornerRounding = 34 
UIObjSetPal_DistributeShapes = 31 
UIObjSetPal_FillColors = 27 
UIObjSetPal_FillPatterns = 28 
UIObjSetPal_LineColors = 24 
UIObjSetPal_LineEnds = 33 
UIObjSetPal_LinePatterns = 26 
UIObjSetPal_LineTool = 42 
UIObjSetPal_LineWeights = 25 
UIObjSetPal_Rectangle_Tool = 37 
UIObjSetPal_RotationTool = 43 
UIObjSetPal_Shadow = 32 
UIObjSetPal_TextColors = 29 
UIObjSetPal_TextTool = 41 
UIObjSetPopup_LineJumpCode = 38 
UIObjSetPopup_LineJumpStyle = 39 
UIObjSetPrintPreview = 7 
UIObjSetShapeSheet = 4 
UIObjSetStencil = 3 
#End Enum 
 
#Public Enum VisUniqueIDArgs 
DeleteGUID = 2 
GetGUID = 0 
GetOrMakeGUID = 1 
#End Enum 
 
#Public Enum VisUnitCodes 
Acre = 36 
AngleUnits = 80 
Centimeters = 69 
CicerosAndDidots = 52 
Ciceros = 54 
Currency = 111 
Date = 40 
DegreeMinSec = 82 
Degrees = 81 
Didots = 53 
DrawingUnits = 64 
DurationUnits = 42 
ElapsedDay = 44 
ElapsedHour = 45 
ElapsedMin = 46 
ElapsedSec = 47 
ElapsedWeek = 43 
FeetAndInches = 67 
Feet = 66 
Hectare = 37 
Inches = 65 
InchFrac = 73 
Kilometers = 72 
Meters = 71 
MileFrac = 74 
Miles = 68 
Millimeters = 70 
Min = 84 
NautMiles = 76 
NoCast = 252 
Number = 32 
PageUnits = 63 
Percent = 33 
PicasAndPoints = 49 
Picas = 51 
Points = 50 
Radians = 83 
Sec = 85 
TypeUnits = 48 
UnitsColor = 251 
UnitsGUID = 95 
UnitsInval = 255 
UnitsNURBS = 138 
UnitsPoint = 225 
UnitsPolyline = 139 
UnitsString = 231 
Yards = 75 
#End Enum 
 
#Public Enum VisVerticalAlignTypes 
VertAlignBottom = 3 
VertAlignMiddle = 2 
VertAlignNone = 0 
VertAlignTop = 1 
#End Enum 
 
#Public Enum VisWindowArrange 
ArrangeCascade = 3 
ArrangeTileHorizontal = 2 
ArrangeTileVertical = 1 
#End Enum 
 
#Public Enum VisWindowFit 
FitNone = 0 
FitPage = 1 
FitWidth = 2 
#End Enum 
 
#Public Enum VisWindowScrollX 
ScrollLeftPage = 2 
ScrollLeft = 0 
ScrollNoneX = 9 
ScrollRightPage = 3 
ScrollRight = 1 
ScrollToLeft = 6 
ScrollToRight = 7 
#End Enum 
 
#Public Enum VisWindowScrollY 
ScrollDownPage = 3 
ScrollDown = 1 
ScrollNoneY = 9 
ScrollToBottom = 7 
ScrollToTop = 6 
ScrollUpPage = 2 
ScrollUp = 0 
#End Enum 
 
#Public Enum VisWindowStates 
WSActive = 0x4000000 
WSAnchorAutoHide = 0x200 
WSAnchorBottom = 0x100 
WSAnchorLeft = 0x20 
WSAnchorMerged = 0x400 
WSAnchorRight = 0x80 
WSAnchorTop = 0x40 
WSDockedBottom = 0x8 
WSDockedLeft = 0x1 
WSDockedRight = 0x4 
WSDockedTop = 0x2 
WSFloating = 0x10 
WSMaximized = 0x40000000 
WSMinimized = 0x20000000 
WSNone = 0x0 
WSRestored = 0x10000000 
WSVisible = 0x8000000 
#End Enum 
 
#Public Enum VisWinTypes 
AnchorBarAddon = 10 
AnchorBarBuiltIn = 6 
Application = 5 
DockedStencilAddon = 11 
DockedStencilBuiltIn = 7 
BuiltinStencilBackgrounds = 0 
BuiltinStencilBorders = 1 
BuiltinStencilContainers = 2
BuiltinStencilCallouts = 3 
BuiltinStencilLegends = 4

Drawing = 1 
DrawingAddon = 8 
Icon = 4 
InvalWinID = -1 
MasterGroupWin = 96 
MasterWin = 64 
PageGroupWin = 160 
PageWin = 128 
Sheet = 3 
Stencil = 2 
StencilAddon = 9 
WinIDCustProp = 1658 
WinIDDrawingExplorer = 1721 
WinIDExternalData = 2044 
WinIDFormulaTracing = 1781 
WinIDMasterExplorer = 1916 
WinIDPanZoom = 1653 
WinIDShapeSearch = 1669 
WinIDSizePos = 1670 
WinIDStencilExplorer = 1796 
WinOther = 0 
#End Enum 
 
#Public Enum VisZoomBehavior 
ZoomInPlaceContainer = 1 
ZoomNone = 0 
ZoomVisio = 2 
ZoomVisioExact = 4 

#Public Enum VisDiagramServices
ServiceNone = 0
ServiceAll = -1
ServiceAutoSizePage = 1
ServiceStructureBasic = 2
ServiceStructureFull = 4
ServiceVersion140 = 7
ServiceVersion150 = 8

}
#End Enum 

$VIS=new-object PSCustomObject -Property $VIS